// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_kernel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.933500,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=944,HLS_SYN_LUT=593,HLS_VERSION=2025_1}" *)

module kernel (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] x_real;
wire   [15:0] x_imag;
reg   [15:0] y_real;
reg   [15:0] y_imag;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8;
reg   [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5_load_reg_582;
reg    ap_block_pp0_stage0_11001;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3_load_reg_587;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2_load_reg_592;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_load_reg_597;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12_load_reg_602;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10_load_reg_607;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9_load_reg_612;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_load_reg_617;
wire   [24:0] prod_i_hr_fu_297_p2;
reg  signed [24:0] prod_i_hr_reg_662;
wire   [24:0] prod_q_hr_fu_306_p2;
reg  signed [24:0] prod_q_hr_reg_667;
wire   [26:0] prod_i_hr_3_fu_315_p2;
reg  signed [26:0] prod_i_hr_3_reg_672;
wire   [26:0] prod_q_hr_3_fu_324_p2;
reg  signed [26:0] prod_q_hr_3_reg_677;
wire   [26:0] prod_i_hr_4_fu_333_p2;
reg  signed [26:0] prod_i_hr_4_reg_682;
wire   [26:0] prod_q_hr_4_fu_342_p2;
reg  signed [26:0] prod_q_hr_4_reg_687;
wire   [24:0] prod_i_hr_6_fu_351_p2;
reg  signed [24:0] prod_i_hr_6_reg_692;
wire   [24:0] prod_q_hr_6_fu_360_p2;
reg  signed [24:0] prod_q_hr_6_reg_697;
wire  signed [26:0] grp_fu_538_p3;
reg  signed [26:0] add_ln81_reg_702;
wire  signed [26:0] grp_fu_552_p3;
reg  signed [26:0] add_ln81_1_reg_707;
wire   [25:0] add_ln81_5_fu_372_p2;
reg   [25:0] add_ln81_5_reg_712;
wire  signed [26:0] grp_fu_545_p3;
reg  signed [26:0] add_ln82_reg_717;
wire  signed [26:0] grp_fu_559_p3;
reg  signed [26:0] add_ln82_1_reg_722;
wire   [25:0] add_ln82_5_fu_384_p2;
reg   [25:0] add_ln82_5_reg_727;
wire   [27:0] acc_real_1_fu_405_p2;
reg   [27:0] acc_real_1_reg_732;
wire   [27:0] acc_imag_1_fu_426_p2;
reg   [27:0] acc_imag_1_reg_738;
wire   [0:0] icmp_ln91_fu_442_p2;
reg   [0:0] icmp_ln91_reg_744;
wire   [0:0] icmp_ln95_fu_458_p2;
reg   [0:0] icmp_ln95_reg_750;
wire    ap_block_pp0_stage0;
wire   [15:0] result_real_1_0_0_05_fu_484_p3;
reg   [15:0] y_real_preg;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] result_imag_1_0_0_06_fu_513_p3;
reg   [15:0] y_imag_preg;
wire  signed [15:0] sext_ln75_fu_262_p0;
wire  signed [15:0] sext_ln78_fu_266_p0;
wire  signed [15:0] sext_ln75_2_fu_270_p0;
wire  signed [15:0] sext_ln78_2_fu_274_p0;
wire  signed [15:0] sext_ln75_6_fu_278_p0;
wire  signed [15:0] sext_ln78_5_fu_282_p0;
wire  signed [15:0] sext_ln75_9_fu_286_p0;
wire  signed [15:0] sext_ln78_7_fu_290_p0;
wire   [8:0] prod_i_hr_fu_297_p1;
wire   [8:0] prod_q_hr_fu_306_p1;
wire   [10:0] prod_i_hr_3_fu_315_p1;
wire   [10:0] prod_q_hr_3_fu_324_p1;
wire   [10:0] prod_i_hr_4_fu_333_p1;
wire   [10:0] prod_q_hr_4_fu_342_p1;
wire   [8:0] prod_i_hr_6_fu_351_p1;
wire   [8:0] prod_q_hr_6_fu_360_p1;
wire  signed [24:0] grp_fu_566_p3;
wire  signed [24:0] grp_fu_522_p3;
wire  signed [25:0] sext_ln81_4_fu_369_p1;
wire  signed [25:0] sext_ln81_3_fu_366_p1;
wire  signed [24:0] grp_fu_574_p3;
wire  signed [24:0] grp_fu_530_p3;
wire  signed [25:0] sext_ln82_7_fu_381_p1;
wire  signed [25:0] sext_ln82_6_fu_378_p1;
wire  signed [27:0] sext_ln81_2_fu_393_p1;
wire  signed [27:0] sext_ln81_1_fu_390_p1;
wire  signed [27:0] sext_ln81_5_fu_402_p1;
wire   [27:0] add_ln81_2_fu_396_p2;
wire  signed [27:0] sext_ln82_5_fu_414_p1;
wire  signed [27:0] sext_ln82_4_fu_411_p1;
wire  signed [27:0] sext_ln82_8_fu_423_p1;
wire   [27:0] add_ln82_2_fu_417_p2;
wire   [12:0] tmp_fu_432_p4;
wire   [12:0] tmp_1_fu_448_p4;
wire   [0:0] icmp_ln92_fu_464_p2;
wire   [0:0] empty_fu_479_p2;
wire   [15:0] result_real_fu_472_p3;
wire   [15:0] trunc_ln93_fu_469_p1;
wire   [0:0] icmp_ln96_fu_493_p2;
wire   [0:0] empty_13_fu_508_p2;
wire   [15:0] result_imag_fu_501_p3;
wire   [15:0] trunc_ln97_fu_498_p1;
wire   [6:0] grp_fu_522_p1;
wire   [6:0] grp_fu_530_p1;
wire   [8:0] grp_fu_538_p1;
wire   [8:0] grp_fu_545_p1;
wire   [8:0] grp_fu_552_p1;
wire   [8:0] grp_fu_559_p1;
wire   [6:0] grp_fu_566_p1;
wire   [6:0] grp_fu_574_p1;
reg    grp_fu_522_ce;
reg    grp_fu_530_ce;
reg    grp_fu_538_ce;
reg    grp_fu_545_ce;
reg    grp_fu_552_ce;
reg    grp_fu_559_ce;
reg    grp_fu_566_ce;
reg    grp_fu_574_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag = 16'd0;
#0 y_real_preg = 16'd0;
#0 y_imag_preg = 16'd0;
end

kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_real(x_real),
    .x_imag(x_imag),
    .y_real(y_real),
    .y_imag(y_imag),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

kernel_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U1(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_load_reg_597),
    .din1(prod_i_hr_fu_297_p1),
    .dout(prod_i_hr_fu_297_p2)
);

kernel_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U2(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_load_reg_617),
    .din1(prod_q_hr_fu_306_p1),
    .dout(prod_q_hr_fu_306_p2)
);

kernel_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U3(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2_load_reg_592),
    .din1(prod_i_hr_3_fu_315_p1),
    .dout(prod_i_hr_3_fu_315_p2)
);

kernel_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U4(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9_load_reg_612),
    .din1(prod_q_hr_3_fu_324_p1),
    .dout(prod_q_hr_3_fu_324_p2)
);

kernel_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U5(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3_load_reg_587),
    .din1(prod_i_hr_4_fu_333_p1),
    .dout(prod_i_hr_4_fu_333_p2)
);

kernel_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U6(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10_load_reg_607),
    .din1(prod_q_hr_4_fu_342_p1),
    .dout(prod_q_hr_4_fu_342_p2)
);

kernel_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U7(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5_load_reg_582),
    .din1(prod_i_hr_6_fu_351_p1),
    .dout(prod_i_hr_6_fu_351_p2)
);

kernel_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U8(
    .din0(kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12_load_reg_602),
    .din1(prod_q_hr_6_fu_360_p1),
    .dout(prod_q_hr_6_fu_360_p2)
);

kernel_mac_muladd_16s_7ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_7ns_25s_25_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln75_fu_262_p0),
    .din1(grp_fu_522_p1),
    .din2(prod_i_hr_reg_662),
    .ce(grp_fu_522_ce),
    .dout(grp_fu_522_p3)
);

kernel_mac_muladd_16s_7ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_7ns_25s_25_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln78_fu_266_p0),
    .din1(grp_fu_530_p1),
    .din2(prod_q_hr_reg_667),
    .ce(grp_fu_530_ce),
    .dout(grp_fu_530_p3)
);

kernel_mac_muladd_16s_9ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_9ns_27s_27_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln75_2_fu_270_p0),
    .din1(grp_fu_538_p1),
    .din2(prod_i_hr_3_reg_672),
    .ce(grp_fu_538_ce),
    .dout(grp_fu_538_p3)
);

kernel_mac_muladd_16s_9ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_9ns_27s_27_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln78_2_fu_274_p0),
    .din1(grp_fu_545_p1),
    .din2(prod_q_hr_3_reg_677),
    .ce(grp_fu_545_ce),
    .dout(grp_fu_545_p3)
);

kernel_mac_muladd_16s_9ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_9ns_27s_27_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln75_6_fu_278_p0),
    .din1(grp_fu_552_p1),
    .din2(prod_i_hr_4_reg_682),
    .ce(grp_fu_552_ce),
    .dout(grp_fu_552_p3)
);

kernel_mac_muladd_16s_9ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_9ns_27s_27_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln78_5_fu_282_p0),
    .din1(grp_fu_559_p1),
    .din2(prod_q_hr_4_reg_687),
    .ce(grp_fu_559_ce),
    .dout(grp_fu_559_p3)
);

kernel_mac_muladd_16s_7ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_7ns_25s_25_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln75_9_fu_286_p0),
    .din1(grp_fu_566_p1),
    .din2(prod_i_hr_6_reg_692),
    .ce(grp_fu_566_ce),
    .dout(grp_fu_566_p3)
);

kernel_mac_muladd_16s_7ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_7ns_25s_25_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln78_7_fu_290_p0),
    .din1(grp_fu_574_p1),
    .din2(prod_q_hr_6_reg_697),
    .ce(grp_fu_574_ce),
    .dout(grp_fu_574_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        y_imag_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            y_imag_preg <= result_imag_1_0_0_06_fu_513_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        y_real_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            y_real_preg <= result_real_1_0_0_05_fu_484_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_imag_1_reg_738 <= acc_imag_1_fu_426_p2;
        acc_real_1_reg_732 <= acc_real_1_fu_405_p2;
        add_ln81_5_reg_712 <= add_ln81_5_fu_372_p2;
        add_ln82_5_reg_727 <= add_ln82_5_fu_384_p2;
        icmp_ln91_reg_744 <= icmp_ln91_fu_442_p2;
        icmp_ln95_reg_750 <= icmp_ln95_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln81_1_reg_707 <= grp_fu_552_p3;
        add_ln81_reg_702 <= grp_fu_538_p3;
        add_ln82_1_reg_722 <= grp_fu_559_p3;
        add_ln82_reg_717 <= grp_fu_545_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag <= x_imag;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real <= x_real;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10_load_reg_607 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12_load_reg_602 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9_load_reg_612 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_load_reg_617 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2_load_reg_592 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3_load_reg_587 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5_load_reg_582 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5;
        kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_load_reg_597 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real;
        prod_i_hr_3_reg_672 <= prod_i_hr_3_fu_315_p2;
        prod_i_hr_4_reg_682 <= prod_i_hr_4_fu_333_p2;
        prod_i_hr_6_reg_692 <= prod_i_hr_6_fu_351_p2;
        prod_i_hr_reg_662 <= prod_i_hr_fu_297_p2;
        prod_q_hr_3_reg_677 <= prod_q_hr_3_fu_324_p2;
        prod_q_hr_4_reg_687 <= prod_q_hr_4_fu_342_p2;
        prod_q_hr_6_reg_697 <= prod_q_hr_6_fu_360_p2;
        prod_q_hr_reg_667 <= prod_q_hr_fu_306_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to4 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_522_ce = 1'b1;
    end else begin
        grp_fu_522_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_530_ce = 1'b1;
    end else begin
        grp_fu_530_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_538_ce = 1'b1;
    end else begin
        grp_fu_538_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_545_ce = 1'b1;
    end else begin
        grp_fu_545_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_552_ce = 1'b1;
    end else begin
        grp_fu_552_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_559_ce = 1'b1;
    end else begin
        grp_fu_559_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_566_ce = 1'b1;
    end else begin
        grp_fu_566_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_574_ce = 1'b1;
    end else begin
        grp_fu_574_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        y_imag = result_imag_1_0_0_06_fu_513_p3;
    end else begin
        y_imag = y_imag_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        y_real = result_real_1_0_0_05_fu_484_p3;
    end else begin
        y_real = y_real_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_imag_1_fu_426_p2 = ($signed(sext_ln82_8_fu_423_p1) + $signed(add_ln82_2_fu_417_p2));

assign acc_real_1_fu_405_p2 = ($signed(sext_ln81_5_fu_402_p1) + $signed(add_ln81_2_fu_396_p2));

assign add_ln81_2_fu_396_p2 = ($signed(sext_ln81_2_fu_393_p1) + $signed(sext_ln81_1_fu_390_p1));

assign add_ln81_5_fu_372_p2 = ($signed(sext_ln81_4_fu_369_p1) + $signed(sext_ln81_3_fu_366_p1));

assign add_ln82_2_fu_417_p2 = ($signed(sext_ln82_5_fu_414_p1) + $signed(sext_ln82_4_fu_411_p1));

assign add_ln82_5_fu_384_p2 = ($signed(sext_ln82_7_fu_381_p1) + $signed(sext_ln82_6_fu_378_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign empty_13_fu_508_p2 = (icmp_ln96_fu_493_p2 | icmp_ln95_reg_750);

assign empty_fu_479_p2 = (icmp_ln92_fu_464_p2 | icmp_ln91_reg_744);

assign grp_fu_522_p1 = 24'd100;

assign grp_fu_530_p1 = 24'd100;

assign grp_fu_538_p1 = 26'd400;

assign grp_fu_545_p1 = 26'd400;

assign grp_fu_552_p1 = 26'd400;

assign grp_fu_559_p1 = 26'd400;

assign grp_fu_566_p1 = 24'd100;

assign grp_fu_574_p1 = 24'd100;

assign icmp_ln91_fu_442_p2 = (($signed(tmp_fu_432_p4) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_464_p2 = (($signed(acc_real_1_reg_732) < $signed(28'd268402688)) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_458_p2 = (($signed(tmp_1_fu_448_p4) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_493_p2 = (($signed(acc_imag_1_reg_738) < $signed(28'd268402688)) ? 1'b1 : 1'b0);

assign prod_i_hr_3_fu_315_p1 = 27'd800;

assign prod_i_hr_4_fu_333_p1 = 27'd800;

assign prod_i_hr_6_fu_351_p1 = 25'd200;

assign prod_i_hr_fu_297_p1 = 25'd200;

assign prod_q_hr_3_fu_324_p1 = 27'd800;

assign prod_q_hr_4_fu_342_p1 = 27'd800;

assign prod_q_hr_6_fu_360_p1 = 25'd200;

assign prod_q_hr_fu_306_p1 = 25'd200;

assign result_imag_1_0_0_06_fu_513_p3 = ((empty_13_fu_508_p2[0:0] == 1'b1) ? result_imag_fu_501_p3 : trunc_ln97_fu_498_p1);

assign result_imag_fu_501_p3 = ((icmp_ln95_reg_750[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign result_real_1_0_0_05_fu_484_p3 = ((empty_fu_479_p2[0:0] == 1'b1) ? result_real_fu_472_p3 : trunc_ln93_fu_469_p1);

assign result_real_fu_472_p3 = ((icmp_ln91_reg_744[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln75_2_fu_270_p0 = kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1;

assign sext_ln75_6_fu_278_p0 = kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4;

assign sext_ln75_9_fu_286_p0 = kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6;

assign sext_ln75_fu_262_p0 = x_real;

assign sext_ln78_2_fu_274_p0 = kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8;

assign sext_ln78_5_fu_282_p0 = kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11;

assign sext_ln78_7_fu_290_p0 = kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13;

assign sext_ln78_fu_266_p0 = x_imag;

assign sext_ln81_1_fu_390_p1 = add_ln81_reg_702;

assign sext_ln81_2_fu_393_p1 = add_ln81_1_reg_707;

assign sext_ln81_3_fu_366_p1 = grp_fu_566_p3;

assign sext_ln81_4_fu_369_p1 = grp_fu_522_p3;

assign sext_ln81_5_fu_402_p1 = $signed(add_ln81_5_reg_712);

assign sext_ln82_4_fu_411_p1 = add_ln82_reg_717;

assign sext_ln82_5_fu_414_p1 = add_ln82_1_reg_722;

assign sext_ln82_6_fu_378_p1 = grp_fu_574_p3;

assign sext_ln82_7_fu_381_p1 = grp_fu_530_p3;

assign sext_ln82_8_fu_423_p1 = $signed(add_ln82_5_reg_727);

assign tmp_1_fu_448_p4 = {{acc_imag_1_fu_426_p2[27:15]}};

assign tmp_fu_432_p4 = {{acc_real_1_fu_405_p2[27:15]}};

assign trunc_ln93_fu_469_p1 = acc_real_1_reg_732[15:0];

assign trunc_ln97_fu_498_p1 = acc_imag_1_reg_738[15:0];

endmodule //kernel
