

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"],
		"CDFG" : "kernel",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "5", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x_real", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_imag", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_real", "Type" : "None", "Direction" : "O"},
			{"Name" : "y_imag", "Type" : "None", "Direction" : "O"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_9ns_25_1_1_U1", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_9ns_25_1_1_U2", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_11ns_27_1_1_U3", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_11ns_27_1_1_U4", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_11ns_27_1_1_U5", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_11ns_27_1_1_U6", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_9ns_25_1_1_U7", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_9ns_25_1_1_U8", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_7ns_25s_25_4_1_U9", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_7ns_25s_25_4_1_U10", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_9ns_27s_27_4_1_U11", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_9ns_27s_27_4_1_U12", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_9ns_27s_27_4_1_U13", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_9ns_27s_27_4_1_U14", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_7ns_25s_25_4_1_U15", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_muladd_16s_7ns_25s_25_4_1_U16", "Parent" : "0"}]}
