// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_kernel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.168000,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=206,HLS_SYN_LUT=500,HLS_VERSION=2025_1}" *)

module kernel (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] x_in;
reg   [15:0] y_out;
reg   [15:0] gain_state;
reg   [15:0] x_in_read_reg_342;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] x_in_read_reg_342_pp0_iter1_reg;
reg   [15:0] x_in_read_reg_342_pp0_iter2_reg;
reg   [15:0] x_in_read_reg_342_pp0_iter3_reg;
wire   [0:0] icmp_ln71_fu_177_p2;
reg   [0:0] icmp_ln71_reg_358;
wire   [31:0] sub_ln81_fu_201_p2;
reg   [31:0] sub_ln81_reg_363;
wire   [15:0] gain_clamped_fu_182_p3;
reg   [15:0] ap_sig_allocacmp_gain_state_load;
wire    ap_block_pp0_stage0;
wire   [15:0] result_1_0_0_s_fu_312_p9;
reg   [15:0] y_out_preg;
reg    ap_block_pp0_stage0_01001;
wire   [13:0] trunc_ln52_fu_125_p1;
wire   [0:0] tmp_fu_117_p3;
wire   [13:0] sub_ln51_fu_129_p2;
wire   [13:0] select_ln51_fu_135_p3;
wire   [13:0] sub_ln59_fu_143_p2;
wire  signed [15:0] error_fu_149_p3;
wire  signed [27:0] shl_ln_fu_165_p3;
wire  signed [31:0] grp_fu_333_p3;
wire   [30:0] tmp_1_fu_190_p3;
wire  signed [31:0] sext_ln81_fu_197_p1;
wire   [24:0] shl_ln1_fu_213_p3;
wire  signed [31:0] sext_ln81_1_fu_220_p1;
wire   [31:0] prod_fu_224_p3;
wire   [11:0] trunc_ln93_fu_260_p1;
wire   [15:0] tmp_cast_fu_242_p4;
wire   [0:0] icmp_ln93_fu_264_p2;
wire   [15:0] add_ln93_fu_270_p2;
wire   [0:0] tmp_2_fu_252_p3;
wire   [15:0] select_ln93_fu_276_p3;
wire   [0:0] icmp_ln88_fu_230_p2;
wire   [0:0] icmp_ln90_fu_236_p2;
wire   [0:0] xor_ln88_fu_292_p2;
wire   [0:0] and_ln90_fu_298_p2;
wire   [15:0] result_1_0_0_s_fu_312_p6;
wire   [15:0] result_1_0_0_s_fu_312_p7;
wire   [1:0] result_1_0_0_s_fu_312_p8;
wire   [15:0] grp_fu_333_p1;
reg    grp_fu_333_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to3;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire  signed [1:0] result_1_0_0_s_fu_312_p1;
wire   [1:0] result_1_0_0_s_fu_312_p3;
wire   [1:0] result_1_0_0_s_fu_312_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 gain_state = 16'd4096;
#0 y_out_preg = 16'd0;
end

kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_in(x_in),
    .y_out(y_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

(* dissolve_hierarchy = "yes" *) kernel_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U1(
    .din0(16'd32767),
    .din1(16'd32768),
    .din2(result_1_0_0_s_fu_312_p6),
    .def(result_1_0_0_s_fu_312_p7),
    .sel(result_1_0_0_s_fu_312_p8),
    .dout(result_1_0_0_s_fu_312_p9)
);

kernel_mac_muladd_16s_16ns_28s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16ns_28s_32_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(error_fu_149_p3),
    .din1(grp_fu_333_p1),
    .din2(shl_ln_fu_165_p3),
    .ce(grp_fu_333_ce),
    .dout(grp_fu_333_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
                gain_state[9] <= 1'b0;
        gain_state[12] <= 1'b1;
        gain_state[15] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        gain_state[9] <= gain_clamped_fu_182_p3[9];
            gain_state[12] <= gain_clamped_fu_182_p3[12];
            gain_state[15] <= gain_clamped_fu_182_p3[15];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        y_out_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            y_out_preg <= result_1_0_0_s_fu_312_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln71_reg_358 <= icmp_ln71_fu_177_p2;
        sub_ln81_reg_363[31 : 15] <= sub_ln81_fu_201_p2[31 : 15];
        x_in_read_reg_342_pp0_iter2_reg <= x_in_read_reg_342_pp0_iter1_reg;
        x_in_read_reg_342_pp0_iter3_reg <= x_in_read_reg_342_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_in_read_reg_342 <= x_in;
        x_in_read_reg_342_pp0_iter1_reg <= x_in_read_reg_342;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_gain_state_load = gain_clamped_fu_182_p3;
    end else begin
        ap_sig_allocacmp_gain_state_load = gain_state;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_333_ce = 1'b1;
    end else begin
        grp_fu_333_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        y_out = result_1_0_0_s_fu_312_p9;
    end else begin
        y_out = y_out_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln93_fu_270_p2 = (tmp_cast_fu_242_p4 + 16'd1);

assign and_ln90_fu_298_p2 = (xor_ln88_fu_292_p2 & icmp_ln90_fu_236_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign error_fu_149_p3 = {{sub_ln59_fu_143_p2}, {2'd0}};

assign gain_clamped_fu_182_p3 = ((icmp_ln71_fu_177_p2[0:0] == 1'b1) ? 16'd32768 : 16'd512);

assign grp_fu_333_p1 = 32'd41728;

assign icmp_ln71_fu_177_p2 = (($signed(grp_fu_333_p3) > $signed(32'd4160749568)) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_230_p2 = (($signed(prod_fu_224_p3) > $signed(32'd134213632)) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_236_p2 = (($signed(prod_fu_224_p3) < $signed(32'd4160749568)) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_264_p2 = ((trunc_ln93_fu_260_p1 != 12'd0) ? 1'b1 : 1'b0);

assign prod_fu_224_p3 = ((icmp_ln71_reg_358[0:0] == 1'b1) ? sub_ln81_reg_363 : sext_ln81_1_fu_220_p1);

assign result_1_0_0_s_fu_312_p6 = ((tmp_2_fu_252_p3[0:0] == 1'b1) ? select_ln93_fu_276_p3 : tmp_cast_fu_242_p4);

assign result_1_0_0_s_fu_312_p7 = 'bx;

assign result_1_0_0_s_fu_312_p8 = {{icmp_ln88_fu_230_p2}, {and_ln90_fu_298_p2}};

assign select_ln51_fu_135_p3 = ((tmp_fu_117_p3[0:0] == 1'b1) ? sub_ln51_fu_129_p2 : trunc_ln52_fu_125_p1);

assign select_ln93_fu_276_p3 = ((icmp_ln93_fu_264_p2[0:0] == 1'b1) ? add_ln93_fu_270_p2 : tmp_cast_fu_242_p4);

assign sext_ln81_1_fu_220_p1 = $signed(shl_ln1_fu_213_p3);

assign sext_ln81_fu_197_p1 = $signed(tmp_1_fu_190_p3);

assign shl_ln1_fu_213_p3 = {{x_in_read_reg_342_pp0_iter3_reg}, {9'd0}};

assign shl_ln_fu_165_p3 = {{ap_sig_allocacmp_gain_state_load}, {12'd0}};

assign sub_ln51_fu_129_p2 = (14'd0 - trunc_ln52_fu_125_p1);

assign sub_ln59_fu_143_p2 = (14'd1000 - select_ln51_fu_135_p3);

assign sub_ln81_fu_201_p2 = ($signed(32'd0) - $signed(sext_ln81_fu_197_p1));

assign tmp_1_fu_190_p3 = {{x_in_read_reg_342_pp0_iter2_reg}, {15'd0}};

assign tmp_2_fu_252_p3 = prod_fu_224_p3[32'd31];

assign tmp_cast_fu_242_p4 = {{prod_fu_224_p3[27:12]}};

assign tmp_fu_117_p3 = x_in[32'd15];

assign trunc_ln52_fu_125_p1 = x_in[13:0];

assign trunc_ln93_fu_260_p1 = prod_fu_224_p3[11:0];

assign xor_ln88_fu_292_p2 = (icmp_ln88_fu_230_p2 ^ 1'd1);

always @ (posedge ap_clk) begin
    gain_state[8:0] <= 9'b000000000;
    gain_state[11:10] <= 2'b00;
    gain_state[14:13] <= 2'b00;
    sub_ln81_reg_363[14:0] <= 15'b000000000000000;
end

endmodule //kernel
