

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "kernel",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_out", "Type" : "None", "Direction" : "O"},
			{"Name" : "p_ZZ6kernel6ap_intILi16EERS_ILi32EEE9shift_reg_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi16EERS_ILi32EEE9shift_reg_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi16EERS_ILi32EEE9shift_reg_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi16EERS_ILi32EEE9shift_reg_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi16EERS_ILi32EEE9shift_reg_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_16_ap_int_32_shift_reg", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"}]}
