"""HLS-Schedule Dialect: third IR layer with complete scheduling and pragma info.

Extends AlgoHWNode with tile sizes, unroll factors, pipeline initiation
intervals, array partitioning, and BRAM bank assignments needed for HLS
code generation.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

from FormaSyn.ir.algo_hw_dialect import AlgoHWNode

logger = logging.getLogger(__name__)


@dataclass
class ScheduleNode(AlgoHWNode):
    """Algo-HW node enriched with HLS scheduling parameters.

    Attributes:
        tile_size: Loop tile size (None if not tiled).
        unroll_factor: HLS UNROLL factor.
        pipeline_ii: Target initiation interval for HLS PIPELINE.
        array_partition_type: 'complete', 'cyclic', 'block', or 'none'.
        bram_banks: Number of BRAM banks allocated to this node
            (filled by MLC backend).
        address_mapping_code: C++ address-mapping snippet generated by
            MLC backend for irregular-access nodes.
    """

    tile_size: Optional[int] = None
    unroll_factor: int = 1
    pipeline_ii: int = 1
    array_partition_type: str = "none"
    bram_banks: int = 0
    address_mapping_code: Optional[str] = None


@dataclass
class HLSScheduleDialect:
    """Top-level container for the HLS-Schedule Dialect IR.

    Attributes:
        variant_id: Inherited from AlgoHWDialect.
        nodes: Mapping of node_id to ScheduleNode.
        input_nodes: Kernel input node ids.
        output_nodes: Kernel output node ids.
        total_dsp_estimate: Aggregate DSP usage.
        total_bram_estimate: Aggregate BRAM usage.
        expected_ii: Overall expected initiation interval.
    """

    variant_id: str
    nodes: dict[str, ScheduleNode] = field(default_factory=dict)
    input_nodes: list[str] = field(default_factory=list)
    output_nodes: list[str] = field(default_factory=list)
    total_dsp_estimate: int = 0
    total_bram_estimate: int = 0
    expected_ii: int = 1

    @classmethod
    def example_ldpc_cnu(cls) -> HLSScheduleDialect:
        """Return a hand-crafted LDPC Min-Sum CNU schedule example."""
        nodes = {
            "msg_in": ScheduleNode(
                node_id="msg_in",
                op_type="input",
                shape=[8],
                data_type="ap_int<8>",
                parallelism=8,
                unroll_factor=8,
                pipeline_ii=1,
                array_partition_type="complete",
            ),
            "sign_map": ScheduleNode(
                node_id="sign_map",
                op_type="map",
                op_detail={"func": "sign"},
                shape=[8],
                input_nodes=["msg_in"],
                data_type="ap_int<1>",
                approx_method="min_sum",
                parallelism=8,
                unroll_factor=8,
                pipeline_ii=1,
                array_partition_type="complete",
            ),
            "abs_map": ScheduleNode(
                node_id="abs_map",
                op_type="map",
                op_detail={"func": "abs"},
                shape=[8],
                input_nodes=["msg_in"],
                data_type="ap_int<7>",
                approx_method="min_sum",
                parallelism=8,
                unroll_factor=8,
                pipeline_ii=1,
                array_partition_type="complete",
            ),
            "xor_reduce": ScheduleNode(
                node_id="xor_reduce",
                op_type="reduce",
                op_detail={"op": "xor", "domain_kind": "neighbors",
                           "exclude_self": True},
                shape=[1],
                input_nodes=["sign_map"],
                is_irregular_access=True,
                csr_ref="H_csr",
                data_type="ap_int<1>",
                approx_method="min_sum",
                parallelism=8,
                unroll_factor=8,
                pipeline_ii=1,
                array_partition_type="cyclic",
                bram_banks=8,
                address_mapping_code="int addr = col_idx[i]; // banked",
            ),
            "min_reduce": ScheduleNode(
                node_id="min_reduce",
                op_type="reduce",
                op_detail={"op": "min", "domain_kind": "neighbors",
                           "exclude_self": True},
                shape=[1],
                input_nodes=["abs_map"],
                is_irregular_access=True,
                csr_ref="H_csr",
                data_type="ap_int<7>",
                approx_method="min_sum",
                parallelism=8,
                unroll_factor=8,
                pipeline_ii=1,
                array_partition_type="cyclic",
                bram_banks=8,
                address_mapping_code="int addr = col_idx[i]; // banked",
            ),
        }
        return cls(
            variant_id="min_sum_int8_p8",
            nodes=nodes,
            input_nodes=["msg_in"],
            output_nodes=["xor_reduce", "min_reduce"],
            total_dsp_estimate=16,
            total_bram_estimate=8,
            expected_ii=1,
        )
