// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_kernel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.933250,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=273,HLS_SYN_LUT=694,HLS_VERSION=2025_1}" *)

module kernel (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [31:0] x_in;
wire   [4:0] bits;
wire   [4:0] frac;
reg   [31:0] y_out;
reg   [4:0] bits_read_reg_202;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] x_in_read_reg_207;
reg   [31:0] x_in_read_reg_207_pp0_iter1_reg;
wire   [30:0] empty_12_fu_138_p3;
reg   [30:0] empty_12_reg_214;
wire  signed [31:0] sext_ln44_fu_197_p1;
reg   [31:0] y_out_preg;
reg    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0;
wire   [5:0] zext_ln35_fu_79_p1;
wire  signed [5:0] add_ln35_fu_82_p2;
wire   [5:0] sub_ln35_fu_96_p2;
wire  signed [31:0] sext_ln35_fu_102_p1;
wire   [32:0] zext_ln35_1_fu_106_p1;
wire  signed [31:0] sext_ln35_1_fu_116_p1;
wire   [32:0] zext_ln35_2_fu_120_p1;
wire   [32:0] lshr_ln35_fu_110_p2;
wire   [32:0] shl_ln35_fu_124_p2;
wire   [0:0] tmp_fu_88_p3;
wire   [30:0] empty_fu_130_p1;
wire   [30:0] empty_11_fu_134_p1;
wire  signed [30:0] max_val_fu_149_p2;
wire   [31:0] zext_ln35_3_fu_146_p1;
wire  signed [31:0] sext_ln36_fu_154_p1;
wire   [31:0] min_val_fu_158_p2;
wire   [0:0] icmp_ln49_fu_169_p2;
wire   [30:0] trunc_ln49_fu_174_p1;
wire   [30:0] trunc_ln49_1_fu_178_p1;
wire   [0:0] icmp_ln47_fu_164_p2;
wire   [30:0] select_ln49_fu_181_p3;
wire   [30:0] result_fu_189_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 y_out_preg = 32'd0;
end

kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_in(x_in),
    .bits(bits),
    .frac(frac),
    .y_out(y_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        y_out_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            y_out_preg <= sext_ln44_fu_197_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bits_read_reg_202 <= bits;
        empty_12_reg_214 <= empty_12_fu_138_p3;
        x_in_read_reg_207 <= x_in;
        x_in_read_reg_207_pp0_iter1_reg <= x_in_read_reg_207;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        y_out = sext_ln44_fu_197_p1;
    end else begin
        y_out = y_out_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_82_p2 = ($signed(zext_ln35_fu_79_p1) + $signed(6'd63));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign empty_11_fu_134_p1 = shl_ln35_fu_124_p2[30:0];

assign empty_12_fu_138_p3 = ((tmp_fu_88_p3[0:0] == 1'b1) ? empty_fu_130_p1 : empty_11_fu_134_p1);

assign empty_fu_130_p1 = lshr_ln35_fu_110_p2[30:0];

assign icmp_ln47_fu_164_p2 = (($signed(sext_ln36_fu_154_p1) < $signed(x_in_read_reg_207_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_169_p2 = (($signed(x_in_read_reg_207_pp0_iter1_reg) < $signed(min_val_fu_158_p2)) ? 1'b1 : 1'b0);

assign lshr_ln35_fu_110_p2 = 33'd1 >> zext_ln35_1_fu_106_p1;

assign max_val_fu_149_p2 = ($signed(empty_12_reg_214) + $signed(31'd2147483647));

assign min_val_fu_158_p2 = (32'd0 - zext_ln35_3_fu_146_p1);

assign result_fu_189_p3 = ((icmp_ln47_fu_164_p2[0:0] == 1'b1) ? max_val_fu_149_p2 : select_ln49_fu_181_p3);

assign select_ln49_fu_181_p3 = ((icmp_ln49_fu_169_p2[0:0] == 1'b1) ? trunc_ln49_fu_174_p1 : trunc_ln49_1_fu_178_p1);

assign sext_ln35_1_fu_116_p1 = add_ln35_fu_82_p2;

assign sext_ln35_fu_102_p1 = $signed(sub_ln35_fu_96_p2);

assign sext_ln36_fu_154_p1 = max_val_fu_149_p2;

assign sext_ln44_fu_197_p1 = $signed(result_fu_189_p3);

assign shl_ln35_fu_124_p2 = 33'd1 << zext_ln35_2_fu_120_p1;

assign sub_ln35_fu_96_p2 = (6'd1 - zext_ln35_fu_79_p1);

assign tmp_fu_88_p3 = add_ln35_fu_82_p2[32'd5];

assign trunc_ln49_1_fu_178_p1 = x_in_read_reg_207_pp0_iter1_reg[30:0];

assign trunc_ln49_fu_174_p1 = min_val_fu_158_p2[30:0];

assign zext_ln35_1_fu_106_p1 = $unsigned(sext_ln35_fu_102_p1);

assign zext_ln35_2_fu_120_p1 = $unsigned(sext_ln35_1_fu_116_p1);

assign zext_ln35_3_fu_146_p1 = empty_12_reg_214;

assign zext_ln35_fu_79_p1 = bits_read_reg_202;

endmodule //kernel
