// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_kernel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.824750,HLS_SYN_LAT=6,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1752,HLS_SYN_LUT=1315,HLS_VERSION=2025_1}" *)

module kernel (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] x_in;
reg   [15:0] y_out;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_31;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_29;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_28;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_27;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_25;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_24;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_23;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_22;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_21;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_20;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_18;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_16;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_15;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_14;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_13;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_12;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_11;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_10;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_9;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_8;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_7;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_6;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_5;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_4;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_3;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_2;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_1;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg;
reg  signed [15:0] x_in_read_reg_1369;
reg    ap_block_pp0_stage0_11001;
reg  signed [15:0] x_in_read_reg_1369_pp0_iter1_reg;
reg  signed [15:0] x_in_read_reg_1369_pp0_iter2_reg;
reg  signed [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374;
reg  signed [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374_pp0_iter1_reg;
reg  signed [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17_load_reg_1380;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_shift_reg_16_reg_1385;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_shift_reg_17_reg_1390;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_shift_reg_20_reg_1395;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_shift_reg_9_load_reg_1400;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_shift_reg_7_load_reg_1405;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410_pp0_iter1_reg;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416_pp0_iter1_reg;
wire   [21:0] add_ln59_1_fu_537_p2;
reg   [21:0] add_ln59_1_reg_1457;
reg   [21:0] add_ln59_1_reg_1457_pp0_iter1_reg;
reg   [21:0] add_ln59_1_reg_1457_pp0_iter2_reg;
wire   [24:0] add_ln59_4_fu_543_p2;
reg   [24:0] add_ln59_4_reg_1462;
reg   [24:0] add_ln59_4_reg_1462_pp0_iter1_reg;
reg   [24:0] add_ln59_4_reg_1462_pp0_iter2_reg;
reg   [24:0] add_ln59_4_reg_1462_pp0_iter3_reg;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467_pp0_iter2_reg;
reg   [15:0] p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26_load_reg_1474;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_11_reg_1480;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486;
reg   [15:0] kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486_pp0_iter2_reg;
reg  signed [15:0] kernel_ap_int_16_ap_int_16_shift_reg_15_reg_1492;
wire   [25:0] mul_ln52_1_fu_661_p2;
reg  signed [25:0] mul_ln52_1_reg_1497;
wire   [25:0] mul_ln52_3_fu_670_p2;
reg  signed [25:0] mul_ln52_3_reg_1502;
wire   [23:0] mul_ln59_fu_679_p2;
reg  signed [23:0] mul_ln59_reg_1507;
wire   [25:0] mul_ln52_7_fu_688_p2;
reg  signed [25:0] mul_ln52_7_reg_1512;
wire   [25:0] mul_ln52_8_fu_697_p2;
reg  signed [25:0] mul_ln52_8_reg_1517;
wire   [22:0] add_ln59_18_fu_786_p2;
reg   [22:0] add_ln59_18_reg_1547;
wire   [24:0] mul_ln52_12_fu_851_p2;
reg  signed [24:0] mul_ln52_12_reg_1557;
wire   [25:0] mul_ln52_13_fu_860_p2;
reg  signed [25:0] mul_ln52_13_reg_1562;
wire   [23:0] add_ln59_20_fu_939_p2;
reg   [23:0] add_ln59_20_reg_1572;
reg   [23:0] add_ln59_20_reg_1572_pp0_iter3_reg;
wire   [23:0] add_ln59_2_fu_1031_p2;
reg   [23:0] add_ln59_2_reg_1587;
wire  signed [25:0] grp_fu_1278_p3;
reg  signed [25:0] add_ln59_3_reg_1592;
wire   [26:0] add_ln59_9_fu_1043_p2;
reg   [26:0] add_ln59_9_reg_1597;
reg   [26:0] add_ln59_9_reg_1597_pp0_iter4_reg;
(* use_dsp48 = "no" *) wire   [25:0] add_ln59_12_fu_1052_p2;
reg   [25:0] add_ln59_12_reg_1602;
reg   [25:0] add_ln59_12_reg_1602_pp0_iter4_reg;
wire   [16:0] add_ln59_15_fu_1057_p2;
reg   [16:0] add_ln59_15_reg_1607;
wire   [26:0] add_ln59_6_fu_1081_p2;
reg   [26:0] add_ln59_6_reg_1618;
wire   [24:0] add_ln59_21_fu_1127_p2;
reg   [24:0] add_ln59_21_reg_1623;
wire   [26:0] add_ln59_24_fu_1139_p2;
reg   [26:0] add_ln59_24_reg_1628;
wire   [25:0] add_ln59_28_fu_1151_p2;
reg   [25:0] add_ln59_28_reg_1633;
wire   [15:0] add_ln72_fu_1215_p2;
reg   [15:0] add_ln72_reg_1638;
wire   [28:0] acc_fu_1221_p2;
reg   [28:0] acc_reg_1643;
reg   [13:0] tmp_25_reg_1648;
wire    ap_block_pp0_stage0;
wire   [15:0] result_1_0_0_05_fu_1261_p3;
reg   [15:0] y_out_preg;
reg    ap_block_pp0_stage0_01001;
wire  signed [15:0] sext_ln52_2_fu_389_p0;
wire   [20:0] tmp_4_fu_393_p3;
wire   [18:0] tmp_5_fu_405_p3;
wire  signed [21:0] sext_ln52_22_fu_413_p1;
wire  signed [21:0] sext_ln52_6_fu_401_p1;
wire   [20:0] tmp_6_fu_423_p3;
wire   [18:0] tmp_7_fu_435_p3;
wire  signed [21:0] sext_ln59_fu_431_p1;
wire  signed [21:0] sext_ln59_3_fu_443_p1;
wire   [22:0] tmp_8_fu_453_p3;
wire   [18:0] tmp_9_fu_465_p3;
wire  signed [24:0] sext_ln52_23_fu_461_p1;
wire  signed [24:0] sext_ln52_24_fu_473_p1;
wire   [23:0] tmp_10_fu_483_p3;
wire   [16:0] tmp_11_fu_495_p3;
wire  signed [24:0] sext_ln52_25_fu_491_p1;
wire  signed [24:0] sext_ln52_27_fu_503_p1;
wire  signed [15:0] sext_ln52_8_fu_513_p0;
wire  signed [15:0] sext_ln52_10_fu_517_p0;
wire  signed [15:0] sext_ln52_11_fu_521_p0;
wire  signed [15:0] sext_ln52_12_fu_525_p0;
wire  signed [15:0] sext_ln52_15_fu_529_p0;
wire  signed [15:0] sext_ln52_17_fu_533_p0;
wire   [21:0] sub_ln52_2_fu_417_p2;
wire   [21:0] add_ln59_32_fu_447_p2;
wire   [24:0] add_ln52_fu_477_p2;
wire   [24:0] sub_ln52_3_fu_507_p2;
wire   [9:0] mul_ln52_1_fu_661_p1;
wire   [9:0] mul_ln52_3_fu_670_p1;
wire   [8:0] mul_ln59_fu_679_p1;
wire  signed [9:0] mul_ln52_7_fu_688_p1;
wire  signed [9:0] mul_ln52_8_fu_697_p1;
wire  signed [15:0] sext_ln59_2_fu_706_p0;
wire  signed [15:0] sext_ln52_20_fu_710_p0;
wire  signed [15:0] sext_ln52_21_fu_714_p0;
wire   [20:0] tmp_18_fu_718_p3;
wire   [18:0] tmp_19_fu_730_p3;
wire  signed [21:0] sext_ln52_33_fu_738_p1;
wire  signed [21:0] sext_ln52_32_fu_726_p1;
wire   [21:0] tmp_20_fu_748_p3;
wire   [19:0] tmp_21_fu_760_p3;
wire  signed [22:0] sext_ln52_35_fu_768_p1;
wire  signed [22:0] sext_ln52_34_fu_756_p1;
wire  signed [15:0] sext_ln52_26_fu_778_p0;
wire   [21:0] sub_ln52_5_fu_742_p2;
wire  signed [22:0] sext_ln59_9_fu_782_p1;
wire   [22:0] sub_ln52_6_fu_772_p2;
wire   [20:0] tmp_fu_792_p3;
wire   [17:0] tmp_1_fu_803_p3;
wire  signed [21:0] sext_ln52_3_fu_810_p1;
wire  signed [21:0] sext_ln52_1_fu_799_p1;
wire   [21:0] tmp_2_fu_820_p3;
wire   [19:0] tmp_3_fu_831_p3;
wire  signed [22:0] sext_ln52_5_fu_838_p1;
wire  signed [22:0] sext_ln52_4_fu_827_p1;
wire   [8:0] mul_ln52_12_fu_851_p1;
wire   [9:0] mul_ln52_13_fu_860_p1;
wire   [22:0] tmp_14_fu_866_p3;
wire   [18:0] tmp_15_fu_877_p3;
wire  signed [23:0] sext_ln59_36_fu_873_p1;
wire  signed [23:0] sext_ln59_37_fu_884_p1;
wire   [20:0] tmp_16_fu_894_p3;
wire   [18:0] tmp_17_fu_905_p3;
wire  signed [22:0] sext_ln52_30_fu_901_p1;
wire  signed [22:0] sext_ln52_31_fu_912_p1;
wire  signed [21:0] sub_ln52_fu_814_p2;
wire   [22:0] add_ln52_1_fu_916_p2;
wire   [23:0] add_ln59_33_fu_888_p2;
wire  signed [23:0] sext_ln59_8_fu_926_p1;
wire   [23:0] add_ln59_19_fu_933_p2;
wire  signed [23:0] sext_ln59_25_fu_930_p1;
wire   [23:0] tmp_12_fu_957_p3;
wire   [16:0] tmp_13_fu_968_p3;
wire  signed [24:0] sext_ln52_28_fu_964_p1;
wire  signed [24:0] sext_ln52_29_fu_975_p1;
wire   [20:0] tmp_22_fu_985_p3;
wire   [17:0] tmp_23_fu_996_p3;
wire  signed [21:0] sext_ln52_37_fu_1003_p1;
wire  signed [21:0] sext_ln52_36_fu_992_p1;
wire  signed [15:0] sext_ln59_38_fu_1013_p0;
wire  signed [24:0] sub_ln52_4_fu_979_p2;
wire  signed [21:0] sub_ln52_7_fu_1007_p2;
wire  signed [22:0] grp_fu_1269_p3;
wire  signed [23:0] sext_ln59_12_fu_1028_p1;
wire  signed [23:0] sext_ln59_11_fu_1025_p1;
wire  signed [25:0] grp_fu_1309_p3;
wire  signed [25:0] grp_fu_1301_p3;
wire  signed [26:0] sext_ln59_18_fu_1040_p1;
wire  signed [26:0] sext_ln59_17_fu_1037_p1;
wire  signed [23:0] grp_fu_1293_p3;
wire  signed [25:0] grp_fu_1285_p3;
wire  signed [25:0] sext_ln59_20_fu_1049_p1;
wire  signed [16:0] sext_ln52_fu_954_p1;
wire  signed [16:0] sext_ln59_38_fu_1013_p1;
wire  signed [22:0] grp_fu_1317_p3;
wire  signed [26:0] sext_ln59_15_fu_1072_p1;
wire  signed [26:0] sext_ln59_14_fu_1069_p1;
wire   [26:0] add_ln59_5_fu_1075_p2;
wire  signed [26:0] sext_ln59_13_fu_1066_p1;
wire   [18:0] tmp_24_fu_1094_p3;
wire  signed [20:0] sext_ln59_39_fu_1101_p1;
wire   [20:0] p_shl_fu_1087_p3;
wire   [20:0] sub_ln59_fu_1105_p2;
wire  signed [22:0] grp_fu_1360_p3;
wire  signed [22:0] sext_ln59_23_fu_1111_p1;
(* use_dsp48 = "no" *) wire   [22:0] add_ln59_17_fu_1115_p2;
wire  signed [24:0] sext_ln59_26_fu_1124_p1;
wire  signed [24:0] sext_ln59_24_fu_1120_p1;
wire  signed [25:0] grp_fu_1351_p3;
wire  signed [25:0] grp_fu_1343_p3;
wire  signed [26:0] sext_ln59_29_fu_1136_p1;
wire  signed [26:0] sext_ln59_28_fu_1133_p1;
wire  signed [24:0] grp_fu_1335_p3;
wire  signed [24:0] grp_fu_1326_p3;
wire  signed [25:0] sext_ln59_33_fu_1148_p1;
wire  signed [25:0] sext_ln59_31_fu_1145_p1;
wire  signed [27:0] sext_ln59_21_fu_1163_p1;
wire  signed [27:0] sext_ln59_19_fu_1160_p1;
wire   [27:0] add_ln59_13_fu_1166_p2;
wire  signed [27:0] sext_ln59_16_fu_1157_p1;
wire  signed [27:0] add_ln59_14_fu_1172_p2;
wire  signed [27:0] sext_ln59_34_fu_1192_p1;
wire  signed [27:0] sext_ln59_30_fu_1189_p1;
wire   [27:0] add_ln59_29_fu_1195_p2;
wire  signed [27:0] sext_ln59_27_fu_1186_p1;
wire  signed [27:0] add_ln59_30_fu_1201_p2;
wire   [15:0] trunc_ln59_1_fu_1207_p1;
wire   [15:0] trunc_ln59_fu_1178_p1;
wire  signed [28:0] sext_ln59_35_fu_1211_p1;
wire  signed [28:0] sext_ln59_22_fu_1182_p1;
wire   [0:0] icmp_ln67_fu_1237_p2;
wire   [0:0] icmp_ln69_fu_1242_p2;
wire   [0:0] empty_fu_1255_p2;
wire   [15:0] result_fu_1247_p3;
wire  signed [6:0] grp_fu_1269_p1;
wire  signed [22:0] grp_fu_1269_p2;
wire   [8:0] grp_fu_1278_p1;
wire   [8:0] grp_fu_1285_p1;
wire  signed [6:0] grp_fu_1293_p1;
wire  signed [8:0] grp_fu_1301_p1;
wire  signed [9:0] grp_fu_1309_p1;
wire  signed [6:0] grp_fu_1317_p1;
wire  signed [8:0] grp_fu_1326_p1;
wire   [8:0] grp_fu_1335_p1;
wire   [8:0] grp_fu_1343_p1;
wire   [8:0] grp_fu_1351_p1;
wire  signed [6:0] grp_fu_1360_p1;
reg    grp_fu_1269_ce;
reg    grp_fu_1278_ce;
reg    grp_fu_1285_ce;
reg    grp_fu_1293_ce;
reg    grp_fu_1301_ce;
reg    grp_fu_1309_ce;
reg    grp_fu_1317_ce;
reg    grp_fu_1326_ce;
reg    grp_fu_1335_ce;
reg    grp_fu_1343_ce;
reg    grp_fu_1351_ce;
reg    grp_fu_1360_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to5;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_31 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_29 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_28 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_27 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_25 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_24 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_23 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_22 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_21 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_20 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_18 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_16 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_15 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_14 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_13 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_12 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_11 = 16'd0;
#0 p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_10 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_9 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_8 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_7 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_6 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_5 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_4 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_3 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_2 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg_1 = 16'd0;
#0 kernel_ap_int_16_ap_int_16_shift_reg = 16'd0;
#0 y_out_preg = 16'd0;
end

kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_in(x_in),
    .y_out(y_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

kernel_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U1(
    .din0(kernel_ap_int_16_ap_int_16_shift_reg_7_load_reg_1405),
    .din1(mul_ln52_1_fu_661_p1),
    .dout(mul_ln52_1_fu_661_p2)
);

kernel_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U2(
    .din0(kernel_ap_int_16_ap_int_16_shift_reg_9_load_reg_1400),
    .din1(mul_ln52_3_fu_670_p1),
    .dout(mul_ln52_3_fu_670_p2)
);

kernel_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U3(
    .din0(kernel_ap_int_16_ap_int_16_shift_reg_20_reg_1395),
    .din1(mul_ln59_fu_679_p1),
    .dout(mul_ln59_fu_679_p2)
);

kernel_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U4(
    .din0(kernel_ap_int_16_ap_int_16_shift_reg_17_reg_1390),
    .din1(mul_ln52_7_fu_688_p1),
    .dout(mul_ln52_7_fu_688_p2)
);

kernel_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U5(
    .din0(kernel_ap_int_16_ap_int_16_shift_reg_16_reg_1385),
    .din1(mul_ln52_8_fu_697_p1),
    .dout(mul_ln52_8_fu_697_p2)
);

kernel_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U6(
    .din0(p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374_pp0_iter1_reg),
    .din1(mul_ln52_12_fu_851_p1),
    .dout(mul_ln52_12_fu_851_p2)
);

kernel_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U7(
    .din0(kernel_ap_int_16_ap_int_16_shift_reg_15_reg_1492),
    .din1(mul_ln52_13_fu_860_p1),
    .dout(mul_ln52_13_fu_860_p2)
);

kernel_mac_muladd_16s_7s_23s_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 23 ),
    .dout_WIDTH( 23 ))
mac_muladd_16s_7s_23s_23_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_2_fu_389_p0),
    .din1(grp_fu_1269_p1),
    .din2(grp_fu_1269_p2),
    .ce(grp_fu_1269_ce),
    .dout(grp_fu_1269_p3)
);

kernel_mac_muladd_16s_9ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_9ns_26s_26_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_8_fu_513_p0),
    .din1(grp_fu_1278_p1),
    .din2(mul_ln52_1_reg_1497),
    .ce(grp_fu_1278_ce),
    .dout(grp_fu_1278_p3)
);

kernel_mac_muladd_16s_9ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_9ns_26s_26_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_10_fu_517_p0),
    .din1(grp_fu_1285_p1),
    .din2(mul_ln52_3_reg_1502),
    .ce(grp_fu_1285_ce),
    .dout(grp_fu_1285_p3)
);

kernel_mac_muladd_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7s_24s_24_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_11_fu_521_p0),
    .din1(grp_fu_1293_p1),
    .din2(mul_ln59_reg_1507),
    .ce(grp_fu_1293_ce),
    .dout(grp_fu_1293_p3)
);

kernel_mac_muladd_16s_9s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_9s_26s_26_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_12_fu_525_p0),
    .din1(grp_fu_1301_p1),
    .din2(mul_ln52_7_reg_1512),
    .ce(grp_fu_1301_ce),
    .dout(grp_fu_1301_p3)
);

kernel_mac_muladd_16s_10s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_10s_26s_26_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_15_fu_529_p0),
    .din1(grp_fu_1309_p1),
    .din2(mul_ln52_8_reg_1517),
    .ce(grp_fu_1309_ce),
    .dout(grp_fu_1309_p3)
);

kernel_mac_muladd_16s_7s_22s_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_16s_7s_22s_23_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_17_fu_533_p0),
    .din1(grp_fu_1317_p1),
    .din2(sub_ln52_fu_814_p2),
    .ce(grp_fu_1317_ce),
    .dout(grp_fu_1317_p3)
);

kernel_mac_muladd_16s_9s_23s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 23 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_9s_23s_25_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17_load_reg_1380),
    .din1(grp_fu_1326_p1),
    .din2(grp_fu_1317_p3),
    .ce(grp_fu_1326_ce),
    .dout(grp_fu_1326_p3)
);

kernel_mac_muladd_16s_9ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_9ns_25s_25_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln59_2_fu_706_p0),
    .din1(grp_fu_1335_p1),
    .din2(mul_ln52_12_reg_1557),
    .ce(grp_fu_1335_ce),
    .dout(grp_fu_1335_p3)
);

kernel_mac_muladd_16s_9ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_9ns_26s_26_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_20_fu_710_p0),
    .din1(grp_fu_1343_p1),
    .din2(mul_ln52_13_reg_1562),
    .ce(grp_fu_1343_ce),
    .dout(grp_fu_1343_p3)
);

kernel_mac_muladd_16s_9ns_25s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_9ns_25s_26_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_21_fu_714_p0),
    .din1(grp_fu_1351_p1),
    .din2(sub_ln52_4_fu_979_p2),
    .ce(grp_fu_1351_ce),
    .dout(grp_fu_1351_p3)
);

kernel_mac_muladd_16s_7s_22s_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_16s_7s_22s_23_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln52_26_fu_778_p0),
    .din1(grp_fu_1360_p1),
    .din2(sub_ln52_7_fu_1007_p2),
    .ce(grp_fu_1360_ce),
    .dout(grp_fu_1360_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        y_out_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
            y_out_preg <= result_1_0_0_05_fu_1261_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_reg_1643 <= acc_fu_1221_p2;
        add_ln59_12_reg_1602 <= add_ln59_12_fu_1052_p2;
        add_ln59_12_reg_1602_pp0_iter4_reg <= add_ln59_12_reg_1602;
        add_ln59_15_reg_1607 <= add_ln59_15_fu_1057_p2;
        add_ln59_1_reg_1457_pp0_iter2_reg[21 : 3] <= add_ln59_1_reg_1457_pp0_iter1_reg[21 : 3];
        add_ln59_20_reg_1572[23 : 3] <= add_ln59_20_fu_939_p2[23 : 3];
        add_ln59_20_reg_1572_pp0_iter3_reg[23 : 3] <= add_ln59_20_reg_1572[23 : 3];
        add_ln59_21_reg_1623 <= add_ln59_21_fu_1127_p2;
        add_ln59_24_reg_1628 <= add_ln59_24_fu_1139_p2;
        add_ln59_28_reg_1633 <= add_ln59_28_fu_1151_p2;
        add_ln59_2_reg_1587 <= add_ln59_2_fu_1031_p2;
        add_ln59_4_reg_1462_pp0_iter2_reg[24 : 1] <= add_ln59_4_reg_1462_pp0_iter1_reg[24 : 1];
        add_ln59_4_reg_1462_pp0_iter3_reg[24 : 1] <= add_ln59_4_reg_1462_pp0_iter2_reg[24 : 1];
        add_ln59_6_reg_1618 <= add_ln59_6_fu_1081_p2;
        add_ln59_9_reg_1597 <= add_ln59_9_fu_1043_p2;
        add_ln59_9_reg_1597_pp0_iter4_reg <= add_ln59_9_reg_1597;
        add_ln72_reg_1638 <= add_ln72_fu_1215_p2;
        kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486_pp0_iter2_reg <= kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486;
        mul_ln52_12_reg_1557 <= mul_ln52_12_fu_851_p2;
        mul_ln52_13_reg_1562 <= mul_ln52_13_fu_860_p2;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467_pp0_iter2_reg <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467;
        tmp_25_reg_1648 <= {{acc_fu_1221_p2[28:15]}};
        x_in_read_reg_1369_pp0_iter2_reg <= x_in_read_reg_1369_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_18_reg_1547[22 : 3] <= add_ln59_18_fu_786_p2[22 : 3];
        add_ln59_1_reg_1457[21 : 3] <= add_ln59_1_fu_537_p2[21 : 3];
        add_ln59_1_reg_1457_pp0_iter1_reg[21 : 3] <= add_ln59_1_reg_1457[21 : 3];
        add_ln59_4_reg_1462[24 : 1] <= add_ln59_4_fu_543_p2[24 : 1];
        add_ln59_4_reg_1462_pp0_iter1_reg[24 : 1] <= add_ln59_4_reg_1462[24 : 1];
        kernel_ap_int_16_ap_int_16_shift_reg_11_reg_1480 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_25;
        kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_24;
        kernel_ap_int_16_ap_int_16_shift_reg_15_reg_1492 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_21;
        kernel_ap_int_16_ap_int_16_shift_reg_16_reg_1385 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_15;
        kernel_ap_int_16_ap_int_16_shift_reg_17_reg_1390 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_14;
        kernel_ap_int_16_ap_int_16_shift_reg_20_reg_1395 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_11;
        kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410 <= kernel_ap_int_16_ap_int_16_shift_reg_2;
        kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410_pp0_iter1_reg <= kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410;
        kernel_ap_int_16_ap_int_16_shift_reg_7_load_reg_1405 <= kernel_ap_int_16_ap_int_16_shift_reg_7;
        kernel_ap_int_16_ap_int_16_shift_reg_9_load_reg_1400 <= kernel_ap_int_16_ap_int_16_shift_reg_9;
        kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416 <= kernel_ap_int_16_ap_int_16_shift_reg;
        kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416_pp0_iter1_reg <= kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416;
        mul_ln52_1_reg_1497 <= mul_ln52_1_fu_661_p2;
        mul_ln52_3_reg_1502 <= mul_ln52_3_fu_670_p2;
        mul_ln52_7_reg_1512 <= mul_ln52_7_fu_688_p2;
        mul_ln52_8_reg_1517 <= mul_ln52_8_fu_697_p2;
        mul_ln59_reg_1507 <= mul_ln59_fu_679_p2;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17_load_reg_1380 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374_pp0_iter1_reg <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26_load_reg_1474 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30;
        x_in_read_reg_1369 <= x_in;
        x_in_read_reg_1369_pp0_iter1_reg <= x_in_read_reg_1369;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln59_3_reg_1592 <= grp_fu_1278_p3;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_31 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_ap_int_16_ap_int_16_shift_reg <= x_in;
        kernel_ap_int_16_ap_int_16_shift_reg_1 <= kernel_ap_int_16_ap_int_16_shift_reg;
        kernel_ap_int_16_ap_int_16_shift_reg_2 <= kernel_ap_int_16_ap_int_16_shift_reg_1;
        kernel_ap_int_16_ap_int_16_shift_reg_3 <= kernel_ap_int_16_ap_int_16_shift_reg_2;
        kernel_ap_int_16_ap_int_16_shift_reg_4 <= kernel_ap_int_16_ap_int_16_shift_reg_3;
        kernel_ap_int_16_ap_int_16_shift_reg_5 <= kernel_ap_int_16_ap_int_16_shift_reg_4;
        kernel_ap_int_16_ap_int_16_shift_reg_6 <= kernel_ap_int_16_ap_int_16_shift_reg_5;
        kernel_ap_int_16_ap_int_16_shift_reg_7 <= kernel_ap_int_16_ap_int_16_shift_reg_6;
        kernel_ap_int_16_ap_int_16_shift_reg_8 <= kernel_ap_int_16_ap_int_16_shift_reg_7;
        kernel_ap_int_16_ap_int_16_shift_reg_9 <= kernel_ap_int_16_ap_int_16_shift_reg_8;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_10 <= kernel_ap_int_16_ap_int_16_shift_reg_9;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_11 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_10;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_12 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_11;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_13 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_12;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_14 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_13;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_15 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_14;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_16 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_15;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_16;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_18 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_17;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_18;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_20 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_19_load_reg_1374;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_21 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_20;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_22 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_21;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_23 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_22;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_24 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_23;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_25 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_24;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_25;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_27 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_28 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_27;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_29 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_28;
        p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30 <= p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_29;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to5 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1269_ce = 1'b1;
    end else begin
        grp_fu_1269_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1278_ce = 1'b1;
    end else begin
        grp_fu_1278_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1285_ce = 1'b1;
    end else begin
        grp_fu_1285_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1293_ce = 1'b1;
    end else begin
        grp_fu_1293_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1301_ce = 1'b1;
    end else begin
        grp_fu_1301_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1309_ce = 1'b1;
    end else begin
        grp_fu_1309_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1317_ce = 1'b1;
    end else begin
        grp_fu_1317_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1326_ce = 1'b1;
    end else begin
        grp_fu_1326_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1335_ce = 1'b1;
    end else begin
        grp_fu_1335_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1343_ce = 1'b1;
    end else begin
        grp_fu_1343_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1351_ce = 1'b1;
    end else begin
        grp_fu_1351_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1360_ce = 1'b1;
    end else begin
        grp_fu_1360_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        y_out = result_1_0_0_05_fu_1261_p3;
    end else begin
        y_out = y_out_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_1221_p2 = ($signed(sext_ln59_35_fu_1211_p1) + $signed(sext_ln59_22_fu_1182_p1));

assign add_ln52_1_fu_916_p2 = ($signed(sext_ln52_30_fu_901_p1) + $signed(sext_ln52_31_fu_912_p1));

assign add_ln52_fu_477_p2 = ($signed(sext_ln52_23_fu_461_p1) + $signed(sext_ln52_24_fu_473_p1));

assign add_ln59_12_fu_1052_p2 = ($signed(grp_fu_1285_p3) + $signed(sext_ln59_20_fu_1049_p1));

assign add_ln59_13_fu_1166_p2 = ($signed(sext_ln59_21_fu_1163_p1) + $signed(sext_ln59_19_fu_1160_p1));

assign add_ln59_14_fu_1172_p2 = ($signed(add_ln59_13_fu_1166_p2) + $signed(sext_ln59_16_fu_1157_p1));

assign add_ln59_15_fu_1057_p2 = ($signed(sext_ln52_fu_954_p1) + $signed(sext_ln59_38_fu_1013_p1));

assign add_ln59_17_fu_1115_p2 = ($signed(grp_fu_1360_p3) + $signed(sext_ln59_23_fu_1111_p1));

assign add_ln59_18_fu_786_p2 = ($signed(sext_ln59_9_fu_782_p1) + $signed(sub_ln52_6_fu_772_p2));

assign add_ln59_19_fu_933_p2 = ($signed(add_ln59_33_fu_888_p2) + $signed(sext_ln59_8_fu_926_p1));

assign add_ln59_1_fu_537_p2 = (sub_ln52_2_fu_417_p2 + add_ln59_32_fu_447_p2);

assign add_ln59_20_fu_939_p2 = ($signed(add_ln59_19_fu_933_p2) + $signed(sext_ln59_25_fu_930_p1));

assign add_ln59_21_fu_1127_p2 = ($signed(sext_ln59_26_fu_1124_p1) + $signed(sext_ln59_24_fu_1120_p1));

assign add_ln59_24_fu_1139_p2 = ($signed(sext_ln59_29_fu_1136_p1) + $signed(sext_ln59_28_fu_1133_p1));

assign add_ln59_28_fu_1151_p2 = ($signed(sext_ln59_33_fu_1148_p1) + $signed(sext_ln59_31_fu_1145_p1));

assign add_ln59_29_fu_1195_p2 = ($signed(sext_ln59_34_fu_1192_p1) + $signed(sext_ln59_30_fu_1189_p1));

assign add_ln59_2_fu_1031_p2 = ($signed(sext_ln59_12_fu_1028_p1) + $signed(sext_ln59_11_fu_1025_p1));

assign add_ln59_30_fu_1201_p2 = ($signed(add_ln59_29_fu_1195_p2) + $signed(sext_ln59_27_fu_1186_p1));

assign add_ln59_32_fu_447_p2 = ($signed(sext_ln59_fu_431_p1) + $signed(sext_ln59_3_fu_443_p1));

assign add_ln59_33_fu_888_p2 = ($signed(sext_ln59_36_fu_873_p1) + $signed(sext_ln59_37_fu_884_p1));

assign add_ln59_4_fu_543_p2 = (add_ln52_fu_477_p2 + sub_ln52_3_fu_507_p2);

assign add_ln59_5_fu_1075_p2 = ($signed(sext_ln59_15_fu_1072_p1) + $signed(sext_ln59_14_fu_1069_p1));

assign add_ln59_6_fu_1081_p2 = ($signed(add_ln59_5_fu_1075_p2) + $signed(sext_ln59_13_fu_1066_p1));

assign add_ln59_9_fu_1043_p2 = ($signed(sext_ln59_18_fu_1040_p1) + $signed(sext_ln59_17_fu_1037_p1));

assign add_ln72_fu_1215_p2 = (trunc_ln59_1_fu_1207_p1 + trunc_ln59_fu_1178_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign empty_fu_1255_p2 = (icmp_ln69_fu_1242_p2 | icmp_ln67_fu_1237_p2);

assign grp_fu_1269_p1 = 23'd8388563;

assign grp_fu_1269_p2 = ($signed(sext_ln52_5_fu_838_p1) - $signed(sext_ln52_4_fu_827_p1));

assign grp_fu_1278_p1 = 26'd427;

assign grp_fu_1285_p1 = 26'd322;

assign grp_fu_1293_p1 = 23'd8388570;

assign grp_fu_1301_p1 = 25'd33554204;

assign grp_fu_1309_p1 = 26'd67108504;

assign grp_fu_1317_p1 = 23'd8388570;

assign grp_fu_1326_p1 = 25'd33554204;

assign grp_fu_1335_p1 = 25'd322;

assign grp_fu_1343_p1 = 26'd427;

assign grp_fu_1351_p1 = 26'd363;

assign grp_fu_1360_p1 = 23'd8388563;

assign icmp_ln67_fu_1237_p2 = (($signed(tmp_25_reg_1648) > $signed(14'd0)) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_1242_p2 = (($signed(acc_reg_1643) < $signed(29'd536838144)) ? 1'b1 : 1'b0);

assign mul_ln52_12_fu_851_p1 = 25'd161;

assign mul_ln52_13_fu_860_p1 = 26'd416;

assign mul_ln52_1_fu_661_p1 = 26'd363;

assign mul_ln52_3_fu_670_p1 = 26'd416;

assign mul_ln52_7_fu_688_p1 = 26'd67108504;

assign mul_ln52_8_fu_697_p1 = 26'd67108461;

assign mul_ln59_fu_679_p1 = 24'd161;

assign p_shl_fu_1087_p3 = {{add_ln59_15_reg_1607}, {4'd0}};

assign result_1_0_0_05_fu_1261_p3 = ((empty_fu_1255_p2[0:0] == 1'b1) ? result_fu_1247_p3 : add_ln72_reg_1638);

assign result_fu_1247_p3 = ((icmp_ln67_fu_1237_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln52_10_fu_517_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_10;

assign sext_ln52_11_fu_521_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_12;

assign sext_ln52_12_fu_525_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_13;

assign sext_ln52_15_fu_529_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_16;

assign sext_ln52_17_fu_533_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_18;

assign sext_ln52_1_fu_799_p1 = $signed(tmp_fu_792_p3);

assign sext_ln52_20_fu_710_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_22;

assign sext_ln52_21_fu_714_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_23;

assign sext_ln52_22_fu_413_p1 = $signed(tmp_5_fu_405_p3);

assign sext_ln52_23_fu_461_p1 = $signed(tmp_8_fu_453_p3);

assign sext_ln52_24_fu_473_p1 = $signed(tmp_9_fu_465_p3);

assign sext_ln52_25_fu_491_p1 = $signed(tmp_10_fu_483_p3);

assign sext_ln52_26_fu_778_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_29;

assign sext_ln52_27_fu_503_p1 = $signed(tmp_11_fu_495_p3);

assign sext_ln52_28_fu_964_p1 = $signed(tmp_12_fu_957_p3);

assign sext_ln52_29_fu_975_p1 = $signed(tmp_13_fu_968_p3);

assign sext_ln52_2_fu_389_p0 = kernel_ap_int_16_ap_int_16_shift_reg_1;

assign sext_ln52_30_fu_901_p1 = $signed(tmp_16_fu_894_p3);

assign sext_ln52_31_fu_912_p1 = $signed(tmp_17_fu_905_p3);

assign sext_ln52_32_fu_726_p1 = $signed(tmp_18_fu_718_p3);

assign sext_ln52_33_fu_738_p1 = $signed(tmp_19_fu_730_p3);

assign sext_ln52_34_fu_756_p1 = $signed(tmp_20_fu_748_p3);

assign sext_ln52_35_fu_768_p1 = $signed(tmp_21_fu_760_p3);

assign sext_ln52_36_fu_992_p1 = $signed(tmp_22_fu_985_p3);

assign sext_ln52_37_fu_1003_p1 = $signed(tmp_23_fu_996_p3);

assign sext_ln52_3_fu_810_p1 = $signed(tmp_1_fu_803_p3);

assign sext_ln52_4_fu_827_p1 = $signed(tmp_2_fu_820_p3);

assign sext_ln52_5_fu_838_p1 = $signed(tmp_3_fu_831_p3);

assign sext_ln52_6_fu_401_p1 = $signed(tmp_4_fu_393_p3);

assign sext_ln52_8_fu_513_p0 = kernel_ap_int_16_ap_int_16_shift_reg_8;

assign sext_ln52_fu_954_p1 = x_in_read_reg_1369_pp0_iter2_reg;

assign sext_ln59_11_fu_1025_p1 = grp_fu_1269_p3;

assign sext_ln59_12_fu_1028_p1 = $signed(add_ln59_1_reg_1457_pp0_iter2_reg);

assign sext_ln59_13_fu_1066_p1 = $signed(add_ln59_2_reg_1587);

assign sext_ln59_14_fu_1069_p1 = add_ln59_3_reg_1592;

assign sext_ln59_15_fu_1072_p1 = $signed(add_ln59_4_reg_1462_pp0_iter3_reg);

assign sext_ln59_16_fu_1157_p1 = $signed(add_ln59_6_reg_1618);

assign sext_ln59_17_fu_1037_p1 = grp_fu_1309_p3;

assign sext_ln59_18_fu_1040_p1 = grp_fu_1301_p3;

assign sext_ln59_19_fu_1160_p1 = $signed(add_ln59_9_reg_1597_pp0_iter4_reg);

assign sext_ln59_20_fu_1049_p1 = grp_fu_1293_p3;

assign sext_ln59_21_fu_1163_p1 = $signed(add_ln59_12_reg_1602_pp0_iter4_reg);

assign sext_ln59_22_fu_1182_p1 = add_ln59_14_fu_1172_p2;

assign sext_ln59_23_fu_1111_p1 = $signed(sub_ln59_fu_1105_p2);

assign sext_ln59_24_fu_1120_p1 = $signed(add_ln59_17_fu_1115_p2);

assign sext_ln59_25_fu_930_p1 = $signed(add_ln59_18_reg_1547);

assign sext_ln59_26_fu_1124_p1 = $signed(add_ln59_20_reg_1572_pp0_iter3_reg);

assign sext_ln59_27_fu_1186_p1 = $signed(add_ln59_21_reg_1623);

assign sext_ln59_28_fu_1133_p1 = grp_fu_1351_p3;

assign sext_ln59_29_fu_1136_p1 = grp_fu_1343_p3;

assign sext_ln59_2_fu_706_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_20;

assign sext_ln59_30_fu_1189_p1 = $signed(add_ln59_24_reg_1628);

assign sext_ln59_31_fu_1145_p1 = grp_fu_1335_p3;

assign sext_ln59_33_fu_1148_p1 = grp_fu_1326_p3;

assign sext_ln59_34_fu_1192_p1 = $signed(add_ln59_28_reg_1633);

assign sext_ln59_35_fu_1211_p1 = add_ln59_30_fu_1201_p2;

assign sext_ln59_36_fu_873_p1 = $signed(tmp_14_fu_866_p3);

assign sext_ln59_37_fu_884_p1 = $signed(tmp_15_fu_877_p3);

assign sext_ln59_38_fu_1013_p0 = p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_31;

assign sext_ln59_38_fu_1013_p1 = sext_ln59_38_fu_1013_p0;

assign sext_ln59_39_fu_1101_p1 = $signed(tmp_24_fu_1094_p3);

assign sext_ln59_3_fu_443_p1 = $signed(tmp_7_fu_435_p3);

assign sext_ln59_8_fu_926_p1 = $signed(add_ln52_1_fu_916_p2);

assign sext_ln59_9_fu_782_p1 = $signed(sub_ln52_5_fu_742_p2);

assign sext_ln59_fu_431_p1 = $signed(tmp_6_fu_423_p3);

assign sub_ln52_2_fu_417_p2 = ($signed(sext_ln52_22_fu_413_p1) - $signed(sext_ln52_6_fu_401_p1));

assign sub_ln52_3_fu_507_p2 = ($signed(sext_ln52_25_fu_491_p1) - $signed(sext_ln52_27_fu_503_p1));

assign sub_ln52_4_fu_979_p2 = ($signed(sext_ln52_28_fu_964_p1) - $signed(sext_ln52_29_fu_975_p1));

assign sub_ln52_5_fu_742_p2 = ($signed(sext_ln52_33_fu_738_p1) - $signed(sext_ln52_32_fu_726_p1));

assign sub_ln52_6_fu_772_p2 = ($signed(sext_ln52_35_fu_768_p1) - $signed(sext_ln52_34_fu_756_p1));

assign sub_ln52_7_fu_1007_p2 = ($signed(sext_ln52_37_fu_1003_p1) - $signed(sext_ln52_36_fu_992_p1));

assign sub_ln52_fu_814_p2 = ($signed(sext_ln52_3_fu_810_p1) - $signed(sext_ln52_1_fu_799_p1));

assign sub_ln59_fu_1105_p2 = ($signed(sext_ln59_39_fu_1101_p1) - $signed(p_shl_fu_1087_p3));

assign tmp_10_fu_483_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_6}, {8'd0}};

assign tmp_11_fu_495_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_6}, {1'd0}};

assign tmp_12_fu_957_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486_pp0_iter2_reg}, {8'd0}};

assign tmp_13_fu_968_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_12_reg_1486_pp0_iter2_reg}, {1'd0}};

assign tmp_14_fu_866_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_11_reg_1480}, {7'd0}};

assign tmp_15_fu_877_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_11_reg_1480}, {3'd0}};

assign tmp_16_fu_894_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26_load_reg_1474}, {5'd0}};

assign tmp_17_fu_905_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_26_load_reg_1474}, {3'd0}};

assign tmp_18_fu_718_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_27}, {5'd0}};

assign tmp_19_fu_730_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_27}, {3'd0}};

assign tmp_1_fu_803_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416_pp0_iter1_reg}, {2'd0}};

assign tmp_20_fu_748_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_28}, {6'd0}};

assign tmp_21_fu_760_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_28}, {4'd0}};

assign tmp_22_fu_985_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467_pp0_iter2_reg}, {5'd0}};

assign tmp_23_fu_996_p3 = {{p_ZZ6kernel6ap_intILi16EERS0_E9shift_reg_30_load_reg_1467_pp0_iter2_reg}, {2'd0}};

assign tmp_24_fu_1094_p3 = {{add_ln59_15_reg_1607}, {2'd0}};

assign tmp_2_fu_820_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410_pp0_iter1_reg}, {6'd0}};

assign tmp_3_fu_831_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_2_load_reg_1410_pp0_iter1_reg}, {4'd0}};

assign tmp_4_fu_393_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_3}, {5'd0}};

assign tmp_5_fu_405_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_3}, {3'd0}};

assign tmp_6_fu_423_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_4}, {5'd0}};

assign tmp_7_fu_435_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_4}, {3'd0}};

assign tmp_8_fu_453_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_5}, {7'd0}};

assign tmp_9_fu_465_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_5}, {3'd0}};

assign tmp_fu_792_p3 = {{kernel_ap_int_16_ap_int_16_shift_reg_load_reg_1416_pp0_iter1_reg}, {5'd0}};

assign trunc_ln59_1_fu_1207_p1 = add_ln59_30_fu_1201_p2[15:0];

assign trunc_ln59_fu_1178_p1 = add_ln59_14_fu_1172_p2[15:0];

always @ (posedge ap_clk) begin
    add_ln59_1_reg_1457[2:0] <= 3'b000;
    add_ln59_1_reg_1457_pp0_iter1_reg[2:0] <= 3'b000;
    add_ln59_1_reg_1457_pp0_iter2_reg[2:0] <= 3'b000;
    add_ln59_4_reg_1462[0] <= 1'b0;
    add_ln59_4_reg_1462_pp0_iter1_reg[0] <= 1'b0;
    add_ln59_4_reg_1462_pp0_iter2_reg[0] <= 1'b0;
    add_ln59_4_reg_1462_pp0_iter3_reg[0] <= 1'b0;
    add_ln59_18_reg_1547[2:0] <= 3'b000;
    add_ln59_20_reg_1572[2:0] <= 3'b000;
    add_ln59_20_reg_1572_pp0_iter3_reg[2:0] <= 3'b000;
end

endmodule //kernel
