// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv_encode_conv_encode,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.728000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=117,HLS_SYN_LUT=261,HLS_VERSION=2025_1}" *)

module conv_encode (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        bit_in_stream_dout,
        bit_in_stream_empty_n,
        bit_in_stream_read,
        y_out_stream_din,
        y_out_stream_full_n,
        y_out_stream_write
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [0:0] bit_in_stream_dout;
input   bit_in_stream_empty_n;
output   bit_in_stream_read;
output  [1:0] y_out_stream_din;
input   y_out_stream_full_n;
output   y_out_stream_write;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [31:0] num_bits;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    Loop_VITIS_LOOP_22_1_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_22_1_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_22_1_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_22_1_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_22_1_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_22_1_proc_U0_bit_in_stream_read;
wire   [1:0] Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_din;
wire    Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_write;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
end

conv_encode_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_bits(num_bits),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

conv_encode_Loop_VITIS_LOOP_22_1_proc Loop_VITIS_LOOP_22_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_22_1_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_22_1_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_22_1_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_22_1_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_22_1_proc_U0_ap_ready),
    .bit_in_stream_dout(bit_in_stream_dout),
    .bit_in_stream_empty_n(bit_in_stream_empty_n),
    .bit_in_stream_read(Loop_VITIS_LOOP_22_1_proc_U0_bit_in_stream_read),
    .y_out_stream_din(Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_din),
    .y_out_stream_full_n(y_out_stream_full_n),
    .y_out_stream_write(Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_write),
    .num_bits(num_bits)
);

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign Loop_VITIS_LOOP_22_1_proc_U0_ap_continue = ap_continue;

assign Loop_VITIS_LOOP_22_1_proc_U0_ap_start = ap_start;

assign ap_done = Loop_VITIS_LOOP_22_1_proc_U0_ap_done;

assign ap_idle = Loop_VITIS_LOOP_22_1_proc_U0_ap_idle;

assign ap_ready = Loop_VITIS_LOOP_22_1_proc_U0_ap_ready;

assign bit_in_stream_read = Loop_VITIS_LOOP_22_1_proc_U0_bit_in_stream_read;

assign y_out_stream_din = Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_din;

assign y_out_stream_write = Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_write;

endmodule //conv_encode
