

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "kernel",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "2", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_out_scale", "Type" : "None", "Direction" : "O"},
			{"Name" : "p_ZZ6kernel6ap_intILi8EERS0_E4taps_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi8EERS0_E4taps_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi8EERS0_E4taps_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi8EERS0_E4taps_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ6kernel6ap_intILi8EERS0_E4taps_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "kernel_ap_int_8_ap_int_8_taps", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"}]}
