-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_encode is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    bit_in_stream_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    bit_in_stream_empty_n : IN STD_LOGIC;
    bit_in_stream_read : OUT STD_LOGIC;
    y_out_stream_din : OUT STD_LOGIC_VECTOR (1 downto 0);
    y_out_stream_full_n : IN STD_LOGIC;
    y_out_stream_write : OUT STD_LOGIC );
end;


architecture behav of conv_encode is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv_encode_conv_encode,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.728000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=117,HLS_SYN_LUT=261,HLS_VERSION=2025_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal num_bits : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_ap_start : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_ap_done : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_bit_in_stream_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_din : STD_LOGIC_VECTOR (1 downto 0);
    signal Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_write : STD_LOGIC;

    component conv_encode_Loop_VITIS_LOOP_22_1_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bit_in_stream_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        bit_in_stream_empty_n : IN STD_LOGIC;
        bit_in_stream_read : OUT STD_LOGIC;
        y_out_stream_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        y_out_stream_full_n : IN STD_LOGIC;
        y_out_stream_write : OUT STD_LOGIC;
        num_bits : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_encode_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        num_bits : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component conv_encode_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        num_bits => num_bits,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    Loop_VITIS_LOOP_22_1_proc_U0 : component conv_encode_Loop_VITIS_LOOP_22_1_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_VITIS_LOOP_22_1_proc_U0_ap_start,
        ap_done => Loop_VITIS_LOOP_22_1_proc_U0_ap_done,
        ap_continue => Loop_VITIS_LOOP_22_1_proc_U0_ap_continue,
        ap_idle => Loop_VITIS_LOOP_22_1_proc_U0_ap_idle,
        ap_ready => Loop_VITIS_LOOP_22_1_proc_U0_ap_ready,
        bit_in_stream_dout => bit_in_stream_dout,
        bit_in_stream_empty_n => bit_in_stream_empty_n,
        bit_in_stream_read => Loop_VITIS_LOOP_22_1_proc_U0_bit_in_stream_read,
        y_out_stream_din => Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_din,
        y_out_stream_full_n => y_out_stream_full_n,
        y_out_stream_write => Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_write,
        num_bits => num_bits);





    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    Loop_VITIS_LOOP_22_1_proc_U0_ap_continue <= ap_continue;
    Loop_VITIS_LOOP_22_1_proc_U0_ap_start <= ap_start;
    ap_done <= Loop_VITIS_LOOP_22_1_proc_U0_ap_done;
    ap_idle <= Loop_VITIS_LOOP_22_1_proc_U0_ap_idle;
    ap_ready <= Loop_VITIS_LOOP_22_1_proc_U0_ap_ready;
    bit_in_stream_read <= Loop_VITIS_LOOP_22_1_proc_U0_bit_in_stream_read;
    y_out_stream_din <= Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_din;
    y_out_stream_write <= Loop_VITIS_LOOP_22_1_proc_U0_y_out_stream_write;
end behav;
