// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_kernel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu200-fsgd2104-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=159,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=4156,HLS_SYN_LUT=4580,HLS_VERSION=2025_1}" *)

module kernel (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 145'd1;
parameter    ap_ST_fsm_state2 = 145'd2;
parameter    ap_ST_fsm_state3 = 145'd4;
parameter    ap_ST_fsm_state4 = 145'd8;
parameter    ap_ST_fsm_state5 = 145'd16;
parameter    ap_ST_fsm_state6 = 145'd32;
parameter    ap_ST_fsm_state7 = 145'd64;
parameter    ap_ST_fsm_state8 = 145'd128;
parameter    ap_ST_fsm_state9 = 145'd256;
parameter    ap_ST_fsm_state10 = 145'd512;
parameter    ap_ST_fsm_state11 = 145'd1024;
parameter    ap_ST_fsm_state12 = 145'd2048;
parameter    ap_ST_fsm_state13 = 145'd4096;
parameter    ap_ST_fsm_state14 = 145'd8192;
parameter    ap_ST_fsm_state15 = 145'd16384;
parameter    ap_ST_fsm_state16 = 145'd32768;
parameter    ap_ST_fsm_state17 = 145'd65536;
parameter    ap_ST_fsm_state18 = 145'd131072;
parameter    ap_ST_fsm_state19 = 145'd262144;
parameter    ap_ST_fsm_state20 = 145'd524288;
parameter    ap_ST_fsm_state21 = 145'd1048576;
parameter    ap_ST_fsm_state22 = 145'd2097152;
parameter    ap_ST_fsm_state23 = 145'd4194304;
parameter    ap_ST_fsm_state24 = 145'd8388608;
parameter    ap_ST_fsm_state25 = 145'd16777216;
parameter    ap_ST_fsm_state26 = 145'd33554432;
parameter    ap_ST_fsm_state27 = 145'd67108864;
parameter    ap_ST_fsm_state28 = 145'd134217728;
parameter    ap_ST_fsm_state29 = 145'd268435456;
parameter    ap_ST_fsm_state30 = 145'd536870912;
parameter    ap_ST_fsm_state31 = 145'd1073741824;
parameter    ap_ST_fsm_state32 = 145'd2147483648;
parameter    ap_ST_fsm_state33 = 145'd4294967296;
parameter    ap_ST_fsm_state34 = 145'd8589934592;
parameter    ap_ST_fsm_state35 = 145'd17179869184;
parameter    ap_ST_fsm_state36 = 145'd34359738368;
parameter    ap_ST_fsm_state37 = 145'd68719476736;
parameter    ap_ST_fsm_state38 = 145'd137438953472;
parameter    ap_ST_fsm_state39 = 145'd274877906944;
parameter    ap_ST_fsm_state40 = 145'd549755813888;
parameter    ap_ST_fsm_state41 = 145'd1099511627776;
parameter    ap_ST_fsm_state42 = 145'd2199023255552;
parameter    ap_ST_fsm_state43 = 145'd4398046511104;
parameter    ap_ST_fsm_state44 = 145'd8796093022208;
parameter    ap_ST_fsm_state45 = 145'd17592186044416;
parameter    ap_ST_fsm_state46 = 145'd35184372088832;
parameter    ap_ST_fsm_state47 = 145'd70368744177664;
parameter    ap_ST_fsm_state48 = 145'd140737488355328;
parameter    ap_ST_fsm_state49 = 145'd281474976710656;
parameter    ap_ST_fsm_state50 = 145'd562949953421312;
parameter    ap_ST_fsm_state51 = 145'd1125899906842624;
parameter    ap_ST_fsm_state52 = 145'd2251799813685248;
parameter    ap_ST_fsm_state53 = 145'd4503599627370496;
parameter    ap_ST_fsm_state54 = 145'd9007199254740992;
parameter    ap_ST_fsm_state55 = 145'd18014398509481984;
parameter    ap_ST_fsm_state56 = 145'd36028797018963968;
parameter    ap_ST_fsm_state57 = 145'd72057594037927936;
parameter    ap_ST_fsm_state58 = 145'd144115188075855872;
parameter    ap_ST_fsm_state59 = 145'd288230376151711744;
parameter    ap_ST_fsm_state60 = 145'd576460752303423488;
parameter    ap_ST_fsm_state61 = 145'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 145'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 145'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 145'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 145'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 145'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 145'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 145'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 145'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 145'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 145'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 145'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 145'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 145'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 145'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 145'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 145'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 145'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 145'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 145'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 145'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 145'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 145'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 145'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 145'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 145'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 145'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 145'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 145'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 145'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 145'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 145'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 145'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 145'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 145'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 145'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 145'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 145'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 145'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 145'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 145'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 145'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 145'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 145'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 145'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 145'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 145'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 145'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 145'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 145'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 145'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 145'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 145'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 145'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 145'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 145'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 145'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 145'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 145'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 145'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 145'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 145'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 145'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 145'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 145'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 145'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 145'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 145'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 145'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 145'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 145'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 145'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 145'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 145'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 145'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 145'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 145'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 145'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 145'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 145'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 145'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state142 = 145'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state143 = 145'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state144 = 145'd11150372599265311570767859136324180752990208;
parameter    ap_ST_fsm_state145 = 145'd22300745198530623141535718272648361505980416;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (256 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [144:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] a;
wire   [63:0] b;
wire   [63:0] c;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem0_blk_n_R;
wire    ap_CS_fsm_state73;
reg    gmem1_blk_n_AR;
reg    gmem1_blk_n_R;
reg    gmem2_blk_n_AW;
wire    ap_CS_fsm_state76;
reg    gmem2_blk_n_W;
wire    ap_CS_fsm_state77;
reg    gmem2_blk_n_B;
wire    ap_CS_fsm_state145;
reg   [63:0] c_read_reg_424;
reg    ap_block_state1;
reg   [59:0] trunc_ln_reg_429;
reg   [59:0] trunc_ln15_1_reg_434;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
wire   [31:0] gmem0_0_ARLEN;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [127:0] gmem0_0_RDATA;
wire   [8:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
reg    gmem1_0_ARVALID;
wire    gmem1_0_ARREADY;
wire   [31:0] gmem1_0_ARLEN;
wire    gmem1_0_RVALID;
reg    gmem1_0_RREADY;
wire   [127:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    ap_block_state2_io;
reg   [127:0] gmem0_addr_read_reg_451;
reg    ap_block_state73;
reg   [127:0] gmem1_addr_read_reg_456;
wire  signed [248:0] tmp_fu_326_p4;
reg  signed [248:0] tmp_reg_461;
wire    ap_CS_fsm_state75;
reg    gmem2_0_AWVALID;
wire    gmem2_0_AWREADY;
wire   [31:0] gmem2_0_AWLEN;
reg    gmem2_0_WVALID;
wire    gmem2_0_WREADY;
wire   [255:0] gmem2_0_WDATA;
wire    gmem2_0_ARREADY;
wire    gmem2_0_RVALID;
wire   [255:0] gmem2_0_RDATA;
wire   [8:0] gmem2_0_RFIFONUM;
wire    gmem2_0_BVALID;
reg    gmem2_0_BREADY;
wire   [63:0] sext_ln15_fu_222_p1;
wire   [63:0] sext_ln15_1_fu_232_p1;
wire   [63:0] sext_ln19_fu_377_p1;
reg   [3:0] i1_fu_114;
wire   [3:0] i_fu_336_p2;
reg   [127:0] shiftreg2_fu_118;
wire   [127:0] zext_ln17_fu_276_p1;
wire    ap_CS_fsm_state74;
reg   [127:0] shiftreg83_fu_122;
wire   [127:0] zext_ln17_1_fu_298_p1;
reg   [248:0] shiftreg104_fu_126;
wire   [119:0] lshr_ln_fu_266_p4;
wire   [7:0] trunc_ln17_fu_262_p1;
wire   [119:0] lshr_ln17_1_fu_288_p4;
wire   [7:0] trunc_ln17_1_fu_284_p1;
wire  signed [8:0] sext_ln17_1_fu_302_p1;
wire  signed [8:0] sext_ln17_fu_280_p1;
wire   [232:0] tmp_1_fu_312_p4;
wire   [8:0] add_ln17_fu_306_p2;
wire  signed [235:0] sext_ln17_2_fu_322_p1;
wire   [58:0] trunc_ln1_fu_368_p4;
wire  signed [251:0] sext_ln15_2_fu_388_p1;
wire   [0:0] icmp_ln15_fu_342_p2;
reg   [144:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
reg    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
reg    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
wire    ap_ST_fsm_state134_blk;
wire    ap_ST_fsm_state135_blk;
wire    ap_ST_fsm_state136_blk;
wire    ap_ST_fsm_state137_blk;
wire    ap_ST_fsm_state138_blk;
wire    ap_ST_fsm_state139_blk;
wire    ap_ST_fsm_state140_blk;
wire    ap_ST_fsm_state141_blk;
wire    ap_ST_fsm_state142_blk;
wire    ap_ST_fsm_state143_blk;
wire    ap_ST_fsm_state144_blk;
reg    ap_ST_fsm_state145_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 145'd1;
#0 i1_fu_114 = 4'd0;
#0 shiftreg2_fu_118 = 128'd0;
#0 shiftreg83_fu_122 = 128'd0;
#0 shiftreg104_fu_126 = 249'd0;
end

kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a(a),
    .b(b),
    .c(c),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

kernel_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(sext_ln15_fu_222_p1),
    .I_CH0_ARLEN(gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

kernel_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(sext_ln15_1_fu_232_p1),
    .I_CH0_ARLEN(gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

kernel_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 67 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem2_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem2_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem2_0_RDATA),
    .I_CH0_RFIFONUM(gmem2_0_RFIFONUM),
    .I_CH0_AWVALID(gmem2_0_AWVALID),
    .I_CH0_AWREADY(gmem2_0_AWREADY),
    .I_CH0_AWADDR(sext_ln19_fu_377_p1),
    .I_CH0_AWLEN(gmem2_0_AWLEN),
    .I_CH0_WVALID(gmem2_0_WVALID),
    .I_CH0_WREADY(gmem2_0_WREADY),
    .I_CH0_WDATA(gmem2_0_WDATA),
    .I_CH0_WSTRB(32'd4294967295),
    .I_CH0_BVALID(gmem2_0_BVALID),
    .I_CH0_BREADY(gmem2_0_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((gmem2_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_fu_114 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
        i1_fu_114 <= i_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                shiftreg104_fu_126[0] <= 1'b0;
        shiftreg104_fu_126[1] <= 1'b0;
        shiftreg104_fu_126[2] <= 1'b0;
        shiftreg104_fu_126[3] <= 1'b0;
        shiftreg104_fu_126[4] <= 1'b0;
        shiftreg104_fu_126[5] <= 1'b0;
        shiftreg104_fu_126[6] <= 1'b0;
        shiftreg104_fu_126[7] <= 1'b0;
        shiftreg104_fu_126[8] <= 1'b0;
        shiftreg104_fu_126[9] <= 1'b0;
        shiftreg104_fu_126[10] <= 1'b0;
        shiftreg104_fu_126[11] <= 1'b0;
        shiftreg104_fu_126[16] <= 1'b0;
        shiftreg104_fu_126[17] <= 1'b0;
        shiftreg104_fu_126[18] <= 1'b0;
        shiftreg104_fu_126[19] <= 1'b0;
        shiftreg104_fu_126[20] <= 1'b0;
        shiftreg104_fu_126[21] <= 1'b0;
        shiftreg104_fu_126[22] <= 1'b0;
        shiftreg104_fu_126[23] <= 1'b0;
        shiftreg104_fu_126[24] <= 1'b0;
        shiftreg104_fu_126[25] <= 1'b0;
        shiftreg104_fu_126[26] <= 1'b0;
        shiftreg104_fu_126[27] <= 1'b0;
        shiftreg104_fu_126[32] <= 1'b0;
        shiftreg104_fu_126[33] <= 1'b0;
        shiftreg104_fu_126[34] <= 1'b0;
        shiftreg104_fu_126[35] <= 1'b0;
        shiftreg104_fu_126[36] <= 1'b0;
        shiftreg104_fu_126[37] <= 1'b0;
        shiftreg104_fu_126[38] <= 1'b0;
        shiftreg104_fu_126[39] <= 1'b0;
        shiftreg104_fu_126[40] <= 1'b0;
        shiftreg104_fu_126[41] <= 1'b0;
        shiftreg104_fu_126[42] <= 1'b0;
        shiftreg104_fu_126[43] <= 1'b0;
        shiftreg104_fu_126[48] <= 1'b0;
        shiftreg104_fu_126[49] <= 1'b0;
        shiftreg104_fu_126[50] <= 1'b0;
        shiftreg104_fu_126[51] <= 1'b0;
        shiftreg104_fu_126[52] <= 1'b0;
        shiftreg104_fu_126[53] <= 1'b0;
        shiftreg104_fu_126[54] <= 1'b0;
        shiftreg104_fu_126[55] <= 1'b0;
        shiftreg104_fu_126[56] <= 1'b0;
        shiftreg104_fu_126[57] <= 1'b0;
        shiftreg104_fu_126[58] <= 1'b0;
        shiftreg104_fu_126[59] <= 1'b0;
        shiftreg104_fu_126[64] <= 1'b0;
        shiftreg104_fu_126[65] <= 1'b0;
        shiftreg104_fu_126[66] <= 1'b0;
        shiftreg104_fu_126[67] <= 1'b0;
        shiftreg104_fu_126[68] <= 1'b0;
        shiftreg104_fu_126[69] <= 1'b0;
        shiftreg104_fu_126[70] <= 1'b0;
        shiftreg104_fu_126[71] <= 1'b0;
        shiftreg104_fu_126[72] <= 1'b0;
        shiftreg104_fu_126[73] <= 1'b0;
        shiftreg104_fu_126[74] <= 1'b0;
        shiftreg104_fu_126[75] <= 1'b0;
        shiftreg104_fu_126[80] <= 1'b0;
        shiftreg104_fu_126[81] <= 1'b0;
        shiftreg104_fu_126[82] <= 1'b0;
        shiftreg104_fu_126[83] <= 1'b0;
        shiftreg104_fu_126[84] <= 1'b0;
        shiftreg104_fu_126[85] <= 1'b0;
        shiftreg104_fu_126[86] <= 1'b0;
        shiftreg104_fu_126[87] <= 1'b0;
        shiftreg104_fu_126[88] <= 1'b0;
        shiftreg104_fu_126[89] <= 1'b0;
        shiftreg104_fu_126[90] <= 1'b0;
        shiftreg104_fu_126[91] <= 1'b0;
        shiftreg104_fu_126[96] <= 1'b0;
        shiftreg104_fu_126[97] <= 1'b0;
        shiftreg104_fu_126[98] <= 1'b0;
        shiftreg104_fu_126[99] <= 1'b0;
        shiftreg104_fu_126[100] <= 1'b0;
        shiftreg104_fu_126[101] <= 1'b0;
        shiftreg104_fu_126[102] <= 1'b0;
        shiftreg104_fu_126[103] <= 1'b0;
        shiftreg104_fu_126[104] <= 1'b0;
        shiftreg104_fu_126[105] <= 1'b0;
        shiftreg104_fu_126[106] <= 1'b0;
        shiftreg104_fu_126[107] <= 1'b0;
        shiftreg104_fu_126[112] <= 1'b0;
        shiftreg104_fu_126[113] <= 1'b0;
        shiftreg104_fu_126[114] <= 1'b0;
        shiftreg104_fu_126[115] <= 1'b0;
        shiftreg104_fu_126[116] <= 1'b0;
        shiftreg104_fu_126[117] <= 1'b0;
        shiftreg104_fu_126[118] <= 1'b0;
        shiftreg104_fu_126[119] <= 1'b0;
        shiftreg104_fu_126[120] <= 1'b0;
        shiftreg104_fu_126[121] <= 1'b0;
        shiftreg104_fu_126[122] <= 1'b0;
        shiftreg104_fu_126[123] <= 1'b0;
        shiftreg104_fu_126[128] <= 1'b0;
        shiftreg104_fu_126[129] <= 1'b0;
        shiftreg104_fu_126[130] <= 1'b0;
        shiftreg104_fu_126[131] <= 1'b0;
        shiftreg104_fu_126[132] <= 1'b0;
        shiftreg104_fu_126[133] <= 1'b0;
        shiftreg104_fu_126[134] <= 1'b0;
        shiftreg104_fu_126[135] <= 1'b0;
        shiftreg104_fu_126[136] <= 1'b0;
        shiftreg104_fu_126[137] <= 1'b0;
        shiftreg104_fu_126[138] <= 1'b0;
        shiftreg104_fu_126[139] <= 1'b0;
        shiftreg104_fu_126[144] <= 1'b0;
        shiftreg104_fu_126[145] <= 1'b0;
        shiftreg104_fu_126[146] <= 1'b0;
        shiftreg104_fu_126[147] <= 1'b0;
        shiftreg104_fu_126[148] <= 1'b0;
        shiftreg104_fu_126[149] <= 1'b0;
        shiftreg104_fu_126[150] <= 1'b0;
        shiftreg104_fu_126[151] <= 1'b0;
        shiftreg104_fu_126[152] <= 1'b0;
        shiftreg104_fu_126[153] <= 1'b0;
        shiftreg104_fu_126[154] <= 1'b0;
        shiftreg104_fu_126[155] <= 1'b0;
        shiftreg104_fu_126[160] <= 1'b0;
        shiftreg104_fu_126[161] <= 1'b0;
        shiftreg104_fu_126[162] <= 1'b0;
        shiftreg104_fu_126[163] <= 1'b0;
        shiftreg104_fu_126[164] <= 1'b0;
        shiftreg104_fu_126[165] <= 1'b0;
        shiftreg104_fu_126[166] <= 1'b0;
        shiftreg104_fu_126[167] <= 1'b0;
        shiftreg104_fu_126[168] <= 1'b0;
        shiftreg104_fu_126[169] <= 1'b0;
        shiftreg104_fu_126[170] <= 1'b0;
        shiftreg104_fu_126[171] <= 1'b0;
        shiftreg104_fu_126[176] <= 1'b0;
        shiftreg104_fu_126[177] <= 1'b0;
        shiftreg104_fu_126[178] <= 1'b0;
        shiftreg104_fu_126[179] <= 1'b0;
        shiftreg104_fu_126[180] <= 1'b0;
        shiftreg104_fu_126[181] <= 1'b0;
        shiftreg104_fu_126[182] <= 1'b0;
        shiftreg104_fu_126[183] <= 1'b0;
        shiftreg104_fu_126[184] <= 1'b0;
        shiftreg104_fu_126[185] <= 1'b0;
        shiftreg104_fu_126[186] <= 1'b0;
        shiftreg104_fu_126[187] <= 1'b0;
        shiftreg104_fu_126[192] <= 1'b0;
        shiftreg104_fu_126[193] <= 1'b0;
        shiftreg104_fu_126[194] <= 1'b0;
        shiftreg104_fu_126[195] <= 1'b0;
        shiftreg104_fu_126[196] <= 1'b0;
        shiftreg104_fu_126[197] <= 1'b0;
        shiftreg104_fu_126[198] <= 1'b0;
        shiftreg104_fu_126[199] <= 1'b0;
        shiftreg104_fu_126[200] <= 1'b0;
        shiftreg104_fu_126[201] <= 1'b0;
        shiftreg104_fu_126[202] <= 1'b0;
        shiftreg104_fu_126[203] <= 1'b0;
        shiftreg104_fu_126[208] <= 1'b0;
        shiftreg104_fu_126[209] <= 1'b0;
        shiftreg104_fu_126[210] <= 1'b0;
        shiftreg104_fu_126[211] <= 1'b0;
        shiftreg104_fu_126[212] <= 1'b0;
        shiftreg104_fu_126[213] <= 1'b0;
        shiftreg104_fu_126[214] <= 1'b0;
        shiftreg104_fu_126[215] <= 1'b0;
        shiftreg104_fu_126[216] <= 1'b0;
        shiftreg104_fu_126[217] <= 1'b0;
        shiftreg104_fu_126[218] <= 1'b0;
        shiftreg104_fu_126[219] <= 1'b0;
        shiftreg104_fu_126[224] <= 1'b0;
        shiftreg104_fu_126[225] <= 1'b0;
        shiftreg104_fu_126[226] <= 1'b0;
        shiftreg104_fu_126[227] <= 1'b0;
        shiftreg104_fu_126[228] <= 1'b0;
        shiftreg104_fu_126[229] <= 1'b0;
        shiftreg104_fu_126[230] <= 1'b0;
        shiftreg104_fu_126[231] <= 1'b0;
        shiftreg104_fu_126[232] <= 1'b0;
        shiftreg104_fu_126[233] <= 1'b0;
        shiftreg104_fu_126[234] <= 1'b0;
        shiftreg104_fu_126[235] <= 1'b0;
        shiftreg104_fu_126[240] <= 1'b0;
        shiftreg104_fu_126[241] <= 1'b0;
        shiftreg104_fu_126[242] <= 1'b0;
        shiftreg104_fu_126[243] <= 1'b0;
        shiftreg104_fu_126[244] <= 1'b0;
        shiftreg104_fu_126[245] <= 1'b0;
        shiftreg104_fu_126[246] <= 1'b0;
        shiftreg104_fu_126[247] <= 1'b0;
        shiftreg104_fu_126[248] <= 1'b0;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
                shiftreg104_fu_126[11 : 0] <= tmp_fu_326_p4[11 : 0];
        shiftreg104_fu_126[27 : 16] <= tmp_fu_326_p4[27 : 16];
        shiftreg104_fu_126[43 : 32] <= tmp_fu_326_p4[43 : 32];
        shiftreg104_fu_126[59 : 48] <= tmp_fu_326_p4[59 : 48];
        shiftreg104_fu_126[75 : 64] <= tmp_fu_326_p4[75 : 64];
        shiftreg104_fu_126[91 : 80] <= tmp_fu_326_p4[91 : 80];
        shiftreg104_fu_126[107 : 96] <= tmp_fu_326_p4[107 : 96];
        shiftreg104_fu_126[123 : 112] <= tmp_fu_326_p4[123 : 112];
        shiftreg104_fu_126[139 : 128] <= tmp_fu_326_p4[139 : 128];
        shiftreg104_fu_126[155 : 144] <= tmp_fu_326_p4[155 : 144];
        shiftreg104_fu_126[171 : 160] <= tmp_fu_326_p4[171 : 160];
        shiftreg104_fu_126[187 : 176] <= tmp_fu_326_p4[187 : 176];
        shiftreg104_fu_126[203 : 192] <= tmp_fu_326_p4[203 : 192];
        shiftreg104_fu_126[219 : 208] <= tmp_fu_326_p4[219 : 208];
        shiftreg104_fu_126[235 : 224] <= tmp_fu_326_p4[235 : 224];
        shiftreg104_fu_126[248 : 240] <= tmp_fu_326_p4[248 : 240];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        shiftreg2_fu_118 <= gmem0_addr_read_reg_451;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
        shiftreg2_fu_118 <= zext_ln17_fu_276_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        shiftreg83_fu_122 <= gmem1_addr_read_reg_456;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
        shiftreg83_fu_122 <= zext_ln17_1_fu_298_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        c_read_reg_424 <= c;
        trunc_ln15_1_reg_434 <= {{b[63:4]}};
        trunc_ln_reg_429 <= {{a[63:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state73) & (1'b1 == ap_CS_fsm_state73))) begin
        gmem0_addr_read_reg_451 <= gmem0_0_RDATA;
        gmem1_addr_read_reg_456 <= gmem1_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        tmp_reg_461[11 : 0] <= tmp_fu_326_p4[11 : 0];
tmp_reg_461[27 : 16] <= tmp_fu_326_p4[27 : 16];
tmp_reg_461[43 : 32] <= tmp_fu_326_p4[43 : 32];
tmp_reg_461[59 : 48] <= tmp_fu_326_p4[59 : 48];
tmp_reg_461[75 : 64] <= tmp_fu_326_p4[75 : 64];
tmp_reg_461[91 : 80] <= tmp_fu_326_p4[91 : 80];
tmp_reg_461[107 : 96] <= tmp_fu_326_p4[107 : 96];
tmp_reg_461[123 : 112] <= tmp_fu_326_p4[123 : 112];
tmp_reg_461[139 : 128] <= tmp_fu_326_p4[139 : 128];
tmp_reg_461[155 : 144] <= tmp_fu_326_p4[155 : 144];
tmp_reg_461[171 : 160] <= tmp_fu_326_p4[171 : 160];
tmp_reg_461[187 : 176] <= tmp_fu_326_p4[187 : 176];
tmp_reg_461[203 : 192] <= tmp_fu_326_p4[203 : 192];
tmp_reg_461[219 : 208] <= tmp_fu_326_p4[219 : 208];
tmp_reg_461[235 : 224] <= tmp_fu_326_p4[235 : 224];
tmp_reg_461[248 : 240] <= tmp_fu_326_p4[248 : 240];
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

assign ap_ST_fsm_state134_blk = 1'b0;

assign ap_ST_fsm_state135_blk = 1'b0;

assign ap_ST_fsm_state136_blk = 1'b0;

assign ap_ST_fsm_state137_blk = 1'b0;

assign ap_ST_fsm_state138_blk = 1'b0;

assign ap_ST_fsm_state139_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state140_blk = 1'b0;

assign ap_ST_fsm_state141_blk = 1'b0;

assign ap_ST_fsm_state142_blk = 1'b0;

assign ap_ST_fsm_state143_blk = 1'b0;

assign ap_ST_fsm_state144_blk = 1'b0;

always @ (*) begin
    if ((gmem2_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state145_blk = 1'b1;
    end else begin
        ap_ST_fsm_state145_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state73)) begin
        ap_ST_fsm_state73_blk = 1'b1;
    end else begin
        ap_ST_fsm_state73_blk = 1'b0;
    end
end

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

always @ (*) begin
    if ((gmem2_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state76_blk = 1'b1;
    end else begin
        ap_ST_fsm_state76_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem2_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem2_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem2_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_0_ARVALID = 1'b1;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state73) & (1'b1 == ap_CS_fsm_state73))) begin
        gmem0_0_RREADY = 1'b1;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_0_ARVALID = 1'b1;
    end else begin
        gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state73) & (1'b1 == ap_CS_fsm_state73))) begin
        gmem1_0_RREADY = 1'b1;
    end else begin
        gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((gmem2_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
        gmem2_0_AWVALID = 1'b1;
    end else begin
        gmem2_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem2_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145))) begin
        gmem2_0_BREADY = 1'b1;
    end else begin
        gmem2_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem2_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        gmem2_0_WVALID = 1'b1;
    end else begin
        gmem2_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        gmem2_blk_n_AW = m_axi_gmem2_AWREADY;
    end else begin
        gmem2_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state145)) begin
        gmem2_blk_n_B = m_axi_gmem2_BVALID;
    end else begin
        gmem2_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        gmem2_blk_n_W = m_axi_gmem2_WREADY;
    end else begin
        gmem2_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if (((1'b0 == ap_block_state73) & (1'b1 == ap_CS_fsm_state73))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            if (((icmp_ln15_fu_342_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state76 : begin
            if (((gmem2_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state77 : begin
            if (((gmem2_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            ap_NS_fsm = ap_ST_fsm_state145;
        end
        ap_ST_fsm_state145 : begin
            if (((gmem2_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state145;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_fu_306_p2 = ($signed(sext_ln17_1_fu_302_p1) + $signed(sext_ln17_fu_280_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state145 = ap_CS_fsm[32'd144];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((gmem1_0_ARREADY == 1'b0) | (gmem0_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state73 = ((gmem1_0_RVALID == 1'b0) | (gmem0_0_RVALID == 1'b0));
end

assign gmem0_0_ARLEN = 64'd1;

assign gmem1_0_ARLEN = 64'd1;

assign gmem2_0_AWLEN = 64'd1;

assign gmem2_0_WDATA = $unsigned(sext_ln15_2_fu_388_p1);

assign i_fu_336_p2 = (i1_fu_114 + 4'd1);

assign icmp_ln15_fu_342_p2 = ((i1_fu_114 == 4'd15) ? 1'b1 : 1'b0);

assign lshr_ln17_1_fu_288_p4 = {{shiftreg83_fu_122[127:8]}};

assign lshr_ln_fu_266_p4 = {{shiftreg2_fu_118[127:8]}};

assign sext_ln15_1_fu_232_p1 = $signed(trunc_ln15_1_reg_434);

assign sext_ln15_2_fu_388_p1 = tmp_reg_461;

assign sext_ln15_fu_222_p1 = $signed(trunc_ln_reg_429);

assign sext_ln17_1_fu_302_p1 = $signed(trunc_ln17_1_fu_284_p1);

assign sext_ln17_2_fu_322_p1 = $signed(tmp_1_fu_312_p4);

assign sext_ln17_fu_280_p1 = $signed(trunc_ln17_fu_262_p1);

assign sext_ln19_fu_377_p1 = $signed(trunc_ln1_fu_368_p4);

assign tmp_1_fu_312_p4 = {{shiftreg104_fu_126[248:16]}};

assign tmp_fu_326_p4 = {{{add_ln17_fu_306_p2}, {4'd0}}, {sext_ln17_2_fu_322_p1}};

assign trunc_ln17_1_fu_284_p1 = shiftreg83_fu_122[7:0];

assign trunc_ln17_fu_262_p1 = shiftreg2_fu_118[7:0];

assign trunc_ln1_fu_368_p4 = {{c_read_reg_424[63:5]}};

assign zext_ln17_1_fu_298_p1 = lshr_ln17_1_fu_288_p4;

assign zext_ln17_fu_276_p1 = lshr_ln_fu_266_p4;

always @ (posedge ap_clk) begin
    tmp_reg_461[15:12] <= 4'b0000;
    tmp_reg_461[31:28] <= 4'b0000;
    tmp_reg_461[47:44] <= 4'b0000;
    tmp_reg_461[63:60] <= 4'b0000;
    tmp_reg_461[79:76] <= 4'b0000;
    tmp_reg_461[95:92] <= 4'b0000;
    tmp_reg_461[111:108] <= 4'b0000;
    tmp_reg_461[127:124] <= 4'b0000;
    tmp_reg_461[143:140] <= 4'b0000;
    tmp_reg_461[159:156] <= 4'b0000;
    tmp_reg_461[175:172] <= 4'b0000;
    tmp_reg_461[191:188] <= 4'b0000;
    tmp_reg_461[207:204] <= 4'b0000;
    tmp_reg_461[223:220] <= 4'b0000;
    tmp_reg_461[239:236] <= 4'b0000;
    shiftreg104_fu_126[15:12] <= 4'b0000;
    shiftreg104_fu_126[31:28] <= 4'b0000;
    shiftreg104_fu_126[47:44] <= 4'b0000;
    shiftreg104_fu_126[63:60] <= 4'b0000;
    shiftreg104_fu_126[79:76] <= 4'b0000;
    shiftreg104_fu_126[95:92] <= 4'b0000;
    shiftreg104_fu_126[111:108] <= 4'b0000;
    shiftreg104_fu_126[127:124] <= 4'b0000;
    shiftreg104_fu_126[143:140] <= 4'b0000;
    shiftreg104_fu_126[159:156] <= 4'b0000;
    shiftreg104_fu_126[175:172] <= 4'b0000;
    shiftreg104_fu_126[191:188] <= 4'b0000;
    shiftreg104_fu_126[207:204] <= 4'b0000;
    shiftreg104_fu_126[223:220] <= 4'b0000;
    shiftreg104_fu_126[239:236] <= 4'b0000;
end

endmodule //kernel
