-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kernel is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "kernel_kernel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.933500,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=944,HLS_SYN_LUT=593,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv25_C8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000011001000";
    constant ap_const_lv27_320 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000001100100000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv28_FFF8000 : STD_LOGIC_VECTOR (27 downto 0) := "1111111111111000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv24_64 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001100100";
    constant ap_const_lv26_190 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110010000";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal x_real : STD_LOGIC_VECTOR (15 downto 0);
    signal x_imag : STD_LOGIC_VECTOR (15 downto 0);
    signal y_real : STD_LOGIC_VECTOR (15 downto 0);
    signal y_imag : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5_load_reg_582 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3_load_reg_587 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2_load_reg_592 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_load_reg_597 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12_load_reg_602 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10_load_reg_607 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9_load_reg_612 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_load_reg_617 : STD_LOGIC_VECTOR (15 downto 0);
    signal prod_i_hr_fu_297_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_i_hr_reg_662 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_q_hr_fu_306_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_q_hr_reg_667 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_i_hr_3_fu_315_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_i_hr_3_reg_672 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_q_hr_3_fu_324_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_q_hr_3_reg_677 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_i_hr_4_fu_333_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_i_hr_4_reg_682 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_q_hr_4_fu_342_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_q_hr_4_reg_687 : STD_LOGIC_VECTOR (26 downto 0);
    signal prod_i_hr_6_fu_351_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_i_hr_6_reg_692 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_q_hr_6_fu_360_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal prod_q_hr_6_reg_697 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_538_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln81_reg_702 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_552_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln81_1_reg_707 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln81_5_fu_372_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln81_5_reg_712 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_545_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln82_reg_717 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_559_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln82_1_reg_722 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln82_5_fu_384_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln82_5_reg_727 : STD_LOGIC_VECTOR (25 downto 0);
    signal acc_real_1_fu_405_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal acc_real_1_reg_732 : STD_LOGIC_VECTOR (27 downto 0);
    signal acc_imag_1_fu_426_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal acc_imag_1_reg_738 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln91_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_744 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_reg_750 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal result_real_1_0_0_05_fu_484_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_real_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal result_imag_1_0_0_06_fu_513_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_imag_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sext_ln75_fu_262_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln78_fu_266_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln75_2_fu_270_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln78_2_fu_274_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln75_6_fu_278_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln78_5_fu_282_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln75_9_fu_286_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln78_7_fu_290_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal prod_i_hr_fu_297_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal prod_q_hr_fu_306_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal prod_i_hr_3_fu_315_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal prod_q_hr_3_fu_324_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal prod_i_hr_4_fu_333_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal prod_q_hr_4_fu_342_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal prod_i_hr_6_fu_351_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal prod_q_hr_6_fu_360_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_566_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_522_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln81_4_fu_369_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln81_3_fu_366_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_574_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_530_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln82_7_fu_381_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln82_6_fu_378_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln81_2_fu_393_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln81_1_fu_390_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln81_5_fu_402_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln81_2_fu_396_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln82_5_fu_414_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln82_4_fu_411_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln82_8_fu_423_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln82_2_fu_417_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_fu_432_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_448_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln92_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_real_fu_472_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln93_fu_469_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln96_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_13_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_imag_fu_501_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln97_fu_498_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_522_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_530_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_538_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_545_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_552_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_559_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_566_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_574_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_522_ce : STD_LOGIC;
    signal grp_fu_530_ce : STD_LOGIC;
    signal grp_fu_538_ce : STD_LOGIC;
    signal grp_fu_545_ce : STD_LOGIC;
    signal grp_fu_552_ce : STD_LOGIC;
    signal grp_fu_559_ce : STD_LOGIC;
    signal grp_fu_566_ce : STD_LOGIC;
    signal grp_fu_574_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to4 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component kernel_mul_16s_9ns_25_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component kernel_mul_16s_11ns_27_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component kernel_mac_muladd_16s_7ns_25s_25_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (24 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component kernel_mac_muladd_16s_9ns_27s_27_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (26 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component kernel_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        x_real : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_imag : OUT STD_LOGIC_VECTOR (15 downto 0);
        y_real : IN STD_LOGIC_VECTOR (15 downto 0);
        y_imag : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component kernel_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        x_real => x_real,
        x_imag => x_imag,
        y_real => y_real,
        y_imag => y_imag,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    mul_16s_9ns_25_1_1_U1 : component kernel_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_load_reg_597,
        din1 => prod_i_hr_fu_297_p1,
        dout => prod_i_hr_fu_297_p2);

    mul_16s_9ns_25_1_1_U2 : component kernel_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_load_reg_617,
        din1 => prod_q_hr_fu_306_p1,
        dout => prod_q_hr_fu_306_p2);

    mul_16s_11ns_27_1_1_U3 : component kernel_mul_16s_11ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 27)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2_load_reg_592,
        din1 => prod_i_hr_3_fu_315_p1,
        dout => prod_i_hr_3_fu_315_p2);

    mul_16s_11ns_27_1_1_U4 : component kernel_mul_16s_11ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 27)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9_load_reg_612,
        din1 => prod_q_hr_3_fu_324_p1,
        dout => prod_q_hr_3_fu_324_p2);

    mul_16s_11ns_27_1_1_U5 : component kernel_mul_16s_11ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 27)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3_load_reg_587,
        din1 => prod_i_hr_4_fu_333_p1,
        dout => prod_i_hr_4_fu_333_p2);

    mul_16s_11ns_27_1_1_U6 : component kernel_mul_16s_11ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 27)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10_load_reg_607,
        din1 => prod_q_hr_4_fu_342_p1,
        dout => prod_q_hr_4_fu_342_p2);

    mul_16s_9ns_25_1_1_U7 : component kernel_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5_load_reg_582,
        din1 => prod_i_hr_6_fu_351_p1,
        dout => prod_i_hr_6_fu_351_p2);

    mul_16s_9ns_25_1_1_U8 : component kernel_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12_load_reg_602,
        din1 => prod_q_hr_6_fu_360_p1,
        dout => prod_q_hr_6_fu_360_p2);

    mac_muladd_16s_7ns_25s_25_4_1_U9 : component kernel_mac_muladd_16s_7ns_25s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        din2_WIDTH => 25,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln75_fu_262_p0,
        din1 => grp_fu_522_p1,
        din2 => prod_i_hr_reg_662,
        ce => grp_fu_522_ce,
        dout => grp_fu_522_p3);

    mac_muladd_16s_7ns_25s_25_4_1_U10 : component kernel_mac_muladd_16s_7ns_25s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        din2_WIDTH => 25,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln78_fu_266_p0,
        din1 => grp_fu_530_p1,
        din2 => prod_q_hr_reg_667,
        ce => grp_fu_530_ce,
        dout => grp_fu_530_p3);

    mac_muladd_16s_9ns_27s_27_4_1_U11 : component kernel_mac_muladd_16s_9ns_27s_27_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 27,
        dout_WIDTH => 27)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln75_2_fu_270_p0,
        din1 => grp_fu_538_p1,
        din2 => prod_i_hr_3_reg_672,
        ce => grp_fu_538_ce,
        dout => grp_fu_538_p3);

    mac_muladd_16s_9ns_27s_27_4_1_U12 : component kernel_mac_muladd_16s_9ns_27s_27_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 27,
        dout_WIDTH => 27)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln78_2_fu_274_p0,
        din1 => grp_fu_545_p1,
        din2 => prod_q_hr_3_reg_677,
        ce => grp_fu_545_ce,
        dout => grp_fu_545_p3);

    mac_muladd_16s_9ns_27s_27_4_1_U13 : component kernel_mac_muladd_16s_9ns_27s_27_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 27,
        dout_WIDTH => 27)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln75_6_fu_278_p0,
        din1 => grp_fu_552_p1,
        din2 => prod_i_hr_4_reg_682,
        ce => grp_fu_552_ce,
        dout => grp_fu_552_p3);

    mac_muladd_16s_9ns_27s_27_4_1_U14 : component kernel_mac_muladd_16s_9ns_27s_27_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 27,
        dout_WIDTH => 27)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln78_5_fu_282_p0,
        din1 => grp_fu_559_p1,
        din2 => prod_q_hr_4_reg_687,
        ce => grp_fu_559_ce,
        dout => grp_fu_559_p3);

    mac_muladd_16s_7ns_25s_25_4_1_U15 : component kernel_mac_muladd_16s_7ns_25s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        din2_WIDTH => 25,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln75_9_fu_286_p0,
        din1 => grp_fu_566_p1,
        din2 => prod_i_hr_6_reg_692,
        ce => grp_fu_566_ce,
        dout => grp_fu_566_p3);

    mac_muladd_16s_7ns_25s_25_4_1_U16 : component kernel_mac_muladd_16s_7ns_25s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        din2_WIDTH => 25,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln78_7_fu_290_p0,
        din1 => grp_fu_574_p1,
        din2 => prod_q_hr_6_reg_697,
        ce => grp_fu_574_ce,
        dout => grp_fu_574_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    y_imag_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                y_imag_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
                    y_imag_preg <= result_imag_1_0_0_06_fu_513_p3;
                end if; 
            end if;
        end if;
    end process;


    y_real_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                y_real_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
                    y_real_preg <= result_real_1_0_0_05_fu_484_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                acc_imag_1_reg_738 <= acc_imag_1_fu_426_p2;
                acc_real_1_reg_732 <= acc_real_1_fu_405_p2;
                add_ln81_5_reg_712 <= add_ln81_5_fu_372_p2;
                add_ln82_5_reg_727 <= add_ln82_5_fu_384_p2;
                icmp_ln91_reg_744 <= icmp_ln91_fu_442_p2;
                icmp_ln95_reg_750 <= icmp_ln95_fu_458_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                add_ln81_1_reg_707 <= grp_fu_552_p3;
                add_ln81_reg_702 <= grp_fu_538_p3;
                add_ln82_1_reg_722 <= grp_fu_559_p3;
                add_ln82_reg_717 <= grp_fu_545_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag <= x_imag;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real <= x_real;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10_load_reg_607 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_10;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12_load_reg_602 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_12;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9_load_reg_612 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_9;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_load_reg_617 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2_load_reg_592 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_2;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3_load_reg_587 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_3;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5_load_reg_582 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_5;
                kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_load_reg_597 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real;
                prod_i_hr_3_reg_672 <= prod_i_hr_3_fu_315_p2;
                prod_i_hr_4_reg_682 <= prod_i_hr_4_fu_333_p2;
                prod_i_hr_6_reg_692 <= prod_i_hr_6_fu_351_p2;
                prod_i_hr_reg_662 <= prod_i_hr_fu_297_p2;
                prod_q_hr_3_reg_677 <= prod_q_hr_3_fu_324_p2;
                prod_q_hr_4_reg_687 <= prod_q_hr_4_fu_342_p2;
                prod_q_hr_6_reg_697 <= prod_q_hr_6_fu_360_p2;
                prod_q_hr_reg_667 <= prod_q_hr_fu_306_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_imag_1_fu_426_p2 <= std_logic_vector(signed(sext_ln82_8_fu_423_p1) + signed(add_ln82_2_fu_417_p2));
    acc_real_1_fu_405_p2 <= std_logic_vector(signed(sext_ln81_5_fu_402_p1) + signed(add_ln81_2_fu_396_p2));
    add_ln81_2_fu_396_p2 <= std_logic_vector(signed(sext_ln81_2_fu_393_p1) + signed(sext_ln81_1_fu_390_p1));
    add_ln81_5_fu_372_p2 <= std_logic_vector(signed(sext_ln81_4_fu_369_p1) + signed(sext_ln81_3_fu_366_p1));
    add_ln82_2_fu_417_p2 <= std_logic_vector(signed(sext_ln82_5_fu_414_p1) + signed(sext_ln82_4_fu_411_p1));
    add_ln82_5_fu_384_p2 <= std_logic_vector(signed(sext_ln82_7_fu_381_p1) + signed(sext_ln82_6_fu_378_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to4)
    begin
        if (((ap_idle_pp0_0to4 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_13_fu_508_p2 <= (icmp_ln96_fu_493_p2 or icmp_ln95_reg_750);
    empty_fu_479_p2 <= (icmp_ln92_fu_464_p2 or icmp_ln91_reg_744);

    grp_fu_522_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_522_ce <= ap_const_logic_1;
        else 
            grp_fu_522_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_522_p1 <= ap_const_lv24_64(7 - 1 downto 0);

    grp_fu_530_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_530_ce <= ap_const_logic_1;
        else 
            grp_fu_530_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_530_p1 <= ap_const_lv24_64(7 - 1 downto 0);

    grp_fu_538_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_538_ce <= ap_const_logic_1;
        else 
            grp_fu_538_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_538_p1 <= ap_const_lv26_190(9 - 1 downto 0);

    grp_fu_545_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_545_ce <= ap_const_logic_1;
        else 
            grp_fu_545_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_545_p1 <= ap_const_lv26_190(9 - 1 downto 0);

    grp_fu_552_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_552_ce <= ap_const_logic_1;
        else 
            grp_fu_552_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_552_p1 <= ap_const_lv26_190(9 - 1 downto 0);

    grp_fu_559_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_559_ce <= ap_const_logic_1;
        else 
            grp_fu_559_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_559_p1 <= ap_const_lv26_190(9 - 1 downto 0);

    grp_fu_566_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_566_ce <= ap_const_logic_1;
        else 
            grp_fu_566_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_566_p1 <= ap_const_lv24_64(7 - 1 downto 0);

    grp_fu_574_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_574_ce <= ap_const_logic_1;
        else 
            grp_fu_574_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_574_p1 <= ap_const_lv24_64(7 - 1 downto 0);
    icmp_ln91_fu_442_p2 <= "1" when (signed(tmp_fu_432_p4) > signed(ap_const_lv13_0)) else "0";
    icmp_ln92_fu_464_p2 <= "1" when (signed(acc_real_1_reg_732) < signed(ap_const_lv28_FFF8000)) else "0";
    icmp_ln95_fu_458_p2 <= "1" when (signed(tmp_1_fu_448_p4) > signed(ap_const_lv13_0)) else "0";
    icmp_ln96_fu_493_p2 <= "1" when (signed(acc_imag_1_reg_738) < signed(ap_const_lv28_FFF8000)) else "0";
    prod_i_hr_3_fu_315_p1 <= ap_const_lv27_320(11 - 1 downto 0);
    prod_i_hr_4_fu_333_p1 <= ap_const_lv27_320(11 - 1 downto 0);
    prod_i_hr_6_fu_351_p1 <= ap_const_lv25_C8(9 - 1 downto 0);
    prod_i_hr_fu_297_p1 <= ap_const_lv25_C8(9 - 1 downto 0);
    prod_q_hr_3_fu_324_p1 <= ap_const_lv27_320(11 - 1 downto 0);
    prod_q_hr_4_fu_342_p1 <= ap_const_lv27_320(11 - 1 downto 0);
    prod_q_hr_6_fu_360_p1 <= ap_const_lv25_C8(9 - 1 downto 0);
    prod_q_hr_fu_306_p1 <= ap_const_lv25_C8(9 - 1 downto 0);
    result_imag_1_0_0_06_fu_513_p3 <= 
        result_imag_fu_501_p3 when (empty_13_fu_508_p2(0) = '1') else 
        trunc_ln97_fu_498_p1;
    result_imag_fu_501_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln95_reg_750(0) = '1') else 
        ap_const_lv16_8000;
    result_real_1_0_0_05_fu_484_p3 <= 
        result_real_fu_472_p3 when (empty_fu_479_p2(0) = '1') else 
        trunc_ln93_fu_469_p1;
    result_real_fu_472_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln91_reg_744(0) = '1') else 
        ap_const_lv16_8000;
    sext_ln75_2_fu_270_p0 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_1;
    sext_ln75_6_fu_278_p0 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_4;
    sext_ln75_9_fu_286_p0 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_real_6;
    sext_ln75_fu_262_p0 <= x_real;
    sext_ln78_2_fu_274_p0 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_8;
    sext_ln78_5_fu_282_p0 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_11;
    sext_ln78_7_fu_290_p0 <= kernel_ap_int_16_ap_int_16_ap_int_16_ap_int_16_shift_reg_imag_13;
    sext_ln78_fu_266_p0 <= x_imag;
        sext_ln81_1_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln81_reg_702),28));

        sext_ln81_2_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln81_1_reg_707),28));

        sext_ln81_3_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_566_p3),26));

        sext_ln81_4_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_522_p3),26));

        sext_ln81_5_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln81_5_reg_712),28));

        sext_ln82_4_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln82_reg_717),28));

        sext_ln82_5_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln82_1_reg_722),28));

        sext_ln82_6_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_574_p3),26));

        sext_ln82_7_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_530_p3),26));

        sext_ln82_8_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln82_5_reg_727),28));

    tmp_1_fu_448_p4 <= acc_imag_1_fu_426_p2(27 downto 15);
    tmp_fu_432_p4 <= acc_real_1_fu_405_p2(27 downto 15);
    trunc_ln93_fu_469_p1 <= acc_real_1_reg_732(16 - 1 downto 0);
    trunc_ln97_fu_498_p1 <= acc_imag_1_reg_738(16 - 1 downto 0);

    y_imag_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_01001, result_imag_1_0_0_06_fu_513_p3, y_imag_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            y_imag <= result_imag_1_0_0_06_fu_513_p3;
        else 
            y_imag <= y_imag_preg;
        end if; 
    end process;


    y_real_assign_proc : process(ap_enable_reg_pp0_iter5, result_real_1_0_0_05_fu_484_p3, y_real_preg, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            y_real <= result_real_1_0_0_05_fu_484_p3;
        else 
            y_real <= y_real_preg;
        end if; 
    end process;

end behav;
